import { Filter, Gauge, ShieldCheck, Sparkles, Wind, Wrench } from "lucide-react";

import type { ApplicationGuideData } from "@/components/templates/application-guide";

export const drumFillingGuide: ApplicationGuideData = {
 slug: "drum-filling",
 title: "Drum & Container Filling",
 titleAccent: "Vacuum Solutions",
 categoryCrumb: { label: "General Industrial Maintenance", anchor: "general-maintenance" },
 seo: {
 title: "Drum & Container Filling Vacuum Solutions",
 description:
 "Industrial vacuum recovery for filling drums, pails and IBCs with powder — capturing the displacement dust pushed out as a rigid container fills, grounded for combustible powder and HEPA-retained for chemical and hazardous materials.",
 },
 tagline: "As the container fills, the air it holds has to go somewhere — and it takes dust with it.",
 heroIntro:
 "Filling a drum, pail or IBC with powder has a dust mechanic all its own: as product goes in, the air the container held is displaced out — and it carries fine dust with it, straight past the fill head. Add that these rigid containers are often filled with chemicals, pigments, resins and hazardous powders, and capture at the fill head becomes both a combustible-dust and an exposure control.",
 badges: [
 { icon: ShieldCheck, title: "Explosion-Safe Design", detail: "Grounded recovery for combustible powder" },
 { icon: Filter, title: "HEPA Filtration", detail: "Chemical & hazardous powders retained" },
 { icon: Wrench, title: "Built to Last", detail: "Rugged. Reliable. PrestiVac." },
 { icon: Gauge, title: "Maximum Uptime", detail: "Drum and IBC throughput" },
 ],
 overview:
 "Rigid-container filling is a close cousin of bag and sack handling, but its signature is displacement dusting. As powder flows into a drum, pail or IBC, it displaces the air already inside, and that rising air escapes around the fill head carrying fine dust with it — a plume generated by the physics of filling rather than by spillage. The materials involved sharpen the concern: drums and IBCs are the workhorses of chemical, pigment, resin and additive handling, so the displaced dust is frequently combustible, and sometimes chemical, hazardous or potent. Capture is positioned at the fill head to catch the displaced plume, grounded and rated where the powder is combustible, and HEPA-retained and sealed where it is hazardous or exposure-limited.",
 capabilities: [
 { icon: Wind, title: "Displacement Dusting", detail: "Air pushed out as the container fills" },
 { icon: Filter, title: "Chemical & Hazardous Powder", detail: "Grounded and HEPA-retained" },
 { icon: Sparkles, title: "Fill-Head Cleanliness", detail: "Station kept clear of spillage" },
 { icon: Gauge, title: "Container Throughput", detail: "Drums, pails and IBCs" },
 ],
 materialsHeading: "Common filled materials",
 materials: [
 "Chemical powders",
 "Pigments & additives",
 "Resin & polymer powder",
 "Mineral & filler powder",
 "Hazardous & potent powder",
 "Mixed filling residue",
 ],
 materialsNote: {
 text: "Combustible and hazardous powders each behave differently, so testing governs —",
 link: { label: "the combustible dust checklist", href: "/resources/combustible-dust-solutions" },
 },
 challengesHeading: "Challenges in drum & container filling",
 challenges: [
 "Displacement dusting — air pushed out of the filling container carries dust",
 "Rigid drums, pails and IBCs behave differently from bags and sacks",
 "Chemical, pigment and resin powders are frequently combustible",
 "Hazardous and potent powders require containment and exposure control",
 "Spillage accumulates around the fill head between fills",
 "Fine powder rises into the operator's breathing zone at the fill point",
 ],
 whyHeading: "Why vacuum recovery?",
 why: [
 "Captures the displaced dust plume right at the fill head",
 "Grounded, rated equipment for combustible chemical and resin powders",
 "HEPA retention and sealed handling for hazardous and potent materials",
 "Reduces spillage and product loss around the station",
 "Keeps the operator's breathing zone clear during filling",
 "Supports combustible-dust and exposure-limit compliance with documented methods",
 ],
 benefits: [
 { title: "Better Safety", detail: "The displaced dust plume is captured before it reaches the operator." },
 { title: "Higher Productivity", detail: "Fill stations stay clean, so drumming and IBC filling keep moving." },
 { title: "Cost Savings", detail: "Less spillage means less product loss and less cleanup labor." },
 { title: "Cleaner Workplace", detail: "HEPA-retained exhaust keeps chemical and hazardous powders out of the air." },
 ],
 recommended: ["explosion-proof-vacuums", "hepa-vacuums", "industrial-vacuums", "pneumatic-vacuums"],
 setup: [
 { step: "Fill station", detail: "Drum, pail or IBC filling head at the source" },
 { step: "Fill-head capture", detail: "Positioned to catch the displaced-air dust plume" },
 { step: "Static-dissipative hose", detail: "Bonded, conductive path end to end" },
 { step: "Rated vacuum unit", detail: "Explosion-proof for combustible powder; HEPA for hazardous materials" },
 { step: "Sealed collection & disposal", detail: "Combustible and hazardous powders contained" },
 ],
 setupNote: {
 text: "Filling bags, sacks and FIBCs is the flexible-container companion —",
 link: { label: "the bagging & dumping guide", href: "/applications/bagging-dumping" },
 textAfter: "covers those.",
 },
 faqs: [
 {
 question: "What is displacement dusting?",
 answer:
 "As powder fills a rigid container, it pushes out the air the container already held, and that escaping air carries fine dust with it around the fill head. It is a dust plume created by the physics of filling rather than by spillage, which is why capture is positioned right at the fill head to catch the displaced air.",
 },
 {
 question: "How is this different from bagging?",
 answer:
 "The mechanics overlap, but rigid drums, pails and IBCs behave differently from flexible bags and sacks, and drum and container filling skews toward chemical, pigment, resin and hazardous powders. Bag, sack and FIBC handling is covered in the bagging and dumping guide; this one focuses on rigid-container filling and its displacement dusting.",
 },
 {
 question: "What about hazardous or chemical powders?",
 answer:
 "Because drums and IBCs are workhorses of chemical handling, the displaced dust is often combustible and sometimes hazardous or potent. Combustible powders call for grounded, rated recovery, while hazardous and exposure-limited materials are captured HEPA-retained and sealed, frequently with recovery dedicated to the material.",
 },
 {
 question: "Where should capture be positioned?",
 answer:
 "At the fill head, where the displaced air escapes — that is where the plume forms, before it rises into the operator's breathing zone. Spillage that lands around the station is then cleared by scheduled housekeeping as the backstop, keeping combustible or hazardous powder from accumulating.",
 },
 ],
 relatedApplications: [
 "Cleanroom Vacuuming",
 "Bagging & dumping",
 "Charging & discharging",
 "Mixing & blending",
 "Bulk material handling",
 "Chemical handling",
 "Spill cleanup",
 ],
 relatedResources: [
 { label: "Explosion Proof Vacuums", href: "/products/explosion-proof-vacuums" },
 { label: "Explosion Proof Vacuum Guide", href: "/resources/explosion-proof-vacuum-guide" },
 { label: "Combustible Dust Solutions", href: "/resources/combustible-dust-solutions" },
 { label: "The NFPA Landscape", href: "/resources/nfpa-guide" },
 ],
};
