import { Filter, Flame, Gauge, ShieldCheck, Sparkles, Wrench } from "lucide-react";

import type { ApplicationGuideData } from "@/components/templates/application-guide";

export const grindingDustGuide: ApplicationGuideData = {
 slug: "grinding-dust",
 title: "Grinding Dust",
 titleAccent: "Recovery",
 categoryCrumb: { label: "Metalworking & Machining", anchor: "metalworking-machining" },
 seo: {
 title: "Grinding Dust Recovery — Metal Fines, Sparks &",
 description:
 "Grinding produces respirable metal fines and sparks from the same operation. How grinding dust behaves, why abrasive and metal fractions mix, and how to recover it without creating an ignition source.",
 },
 tagline: "Sparks and fuel from one operation",
 heroIntro:
 "Grinding is the operation that manufactures its own hazard twice over. It reduces metal to the fine, reactive fraction that behaves as a combustible dust, and in the same motion throws incandescent particles across the work area. Nothing else in a fabrication shop combines fuel production and ignition quite so efficiently.",
 badges: [
 { icon: ShieldCheck, title: "Explosion-Safe Design", detail: "Grounded, bonded, conductive recovery path" },
 { icon: Flame, title: "Sparks From The Process", detail: "Ignition source and fuel from one operation" },
 { icon: Filter, title: "HEPA Filtration", detail: "Tested 99.99% at 0.3 um" },
 { icon: Gauge, title: "Abrasive Duty", detail: "Built for mixed metal and wheel debris" },
 ],
 overview:
 "The dust from a grinder is not one material. It is metal removed from the workpiece, abrasive shed from the wheel, and — depending on the job — coating, weld slag, mill scale or rust. The metal fraction is what matters most: fine, freshly exposed and in the case of aluminium, magnesium or titanium genuinely reactive. Those fines settle on the machine, the bench, the floor and every horizontal surface within reach, and grinding sparks travel far enough to find them. That is why grinding areas repeatedly appear in incident reports, and why housekeeping there is not a tidiness question. Recovery has to remove accumulation without providing another ignition source, which rules out compressed-air blowdown and shop vacuums, and it has to survive abrasive material passing through it every day.",
 capabilities: [
 { icon: ShieldCheck, title: "Conductive throughout", detail: "Grounded and bonded from hose tip to collection container, with anti-static accessories rather than plastic hose." },
 { icon: Wrench, title: "Abrasive-tolerant construction", detail: "Grinding debris wears hoses, wands and separation surfaces — serviceable wear parts matter more than peak suction figures." },
 { icon: Filter, title: "Retained filtration", detail: "HEPA retention where respirable metal fines are generated, so cleaning does not return them to the breathing zone." },
 { icon: Sparkles, title: "Immersion option for reactive fines", detail: "Where aluminium, magnesium or titanium is ground, recovered fines can be kept wetted rather than accumulating dry." },
 ],
 materialsHeading: "Materials generated by grinding",
 materials: [
 "Steel and cast iron fines, often mixed with mill scale and rust",
 "Stainless steel fines — hexavalent chromium is a recognised exposure risk in stainless grinding and welding",
 "Aluminium fines, reactive and water-sensitive when hot",
 "Magnesium and titanium fines, readily ignitable and burning at extreme temperature",
 "Abrasive shed from wheels, belts and flap discs",
 "Coating, paint and weld slag removed alongside the base metal",
 ],
 materialsNote: {
 text: "Metal dust behaviour depends on the metal and the particle size, and reactive fines change the recovery decision entirely.",
 link: { label: "Combustible metal dust guide", href: "/materials/combustible-metal-dust" },
 },
 challengesHeading: "Why grinding areas are difficult",
 challenges: [
 "The process supplies both fuel and ignition: fine metal is produced and incandescent particles are thrown in the same operation.",
 "Sparks travel: grinding debris reaches accumulations well outside the immediate work area, including under benches and behind equipment.",
 "Mixed material: metal, abrasive, coating and slag arrive together, complicating both recovery and disposal.",
 "Abrasive wear: grinding debris is hard on hoses, wands and separation surfaces, so equipment not built for it degrades quickly.",
 "Reactive fines: aluminium, magnesium and titanium grinding produces material where water is the wrong response and heat can build inside collected debris.",
 "Respirable exposure: stainless grinding raises hexavalent chromium concerns, addressed by OSHA under 29 CFR 1910.1026, in addition to general metal-dust exposure.",
 ],
 whyHeading: "Why vacuum recovery rather than air or a broom",
 why: [
 "Compressed-air blowdown suspends metal fines directly into the air of a room containing an active ignition source — it is the worst available option in a grinding bay.",
 "Sweeping lofts the fine fraction and leaves the accumulations above head height untouched, which is where the secondary-event fuel sits.",
 "A shop vacuum brings a brushed motor, a static-accumulating plastic hose and filtration that returns fines to the room into exactly the wrong environment.",
 "Vacuum recovery removes material from the building rather than relocating it, provided the equipment is grounded, bonded and suitable for the classification.",
 "Retained filtration keeps respirable metal fines out of the breathing zone during the cleaning pass itself.",
 "Recovering promptly limits how much fuel is available when the next spark lands somewhere unplanned.",
 ],
 benefits: [
 { title: "Ignition risk reduced at source", detail: "Removing accumulation removes the fuel that grinding sparks would otherwise find, which is the control with the most leverage." },
 { title: "Exposure controlled", detail: "Retained HEPA filtration addresses respirable metal fines rather than redistributing them around the shop." },
 { title: "Equipment that survives the duty", detail: "Abrasive-tolerant construction and serviceable wear parts, instead of a machine that degrades in a month." },
 { title: "Cleaner machines and better finish", detail: "Grinding debris off machine surfaces and guarding means less contamination transferred onto the next workpiece." },
 ],
 recommended: ["explosion-proof-vacuums", "industrial-vacuums", "wet-dry-systems", "hepa-vacuums"],
 setup: [
 { step: "Identify the metals ground in the area", detail: "Reactive metals change the recovery method. A bay that grinds steel and occasionally titanium has to be specified for the titanium." },
 { step: "Confirm the area classification", detail: "Your electrical or process engineer assigns it. Where conductive metal dust is present in hazardous quantities the requirements tighten." },
 { step: "Specify the conductive chain", detail: "Anti-static hose, conductive wands and bonded accessories — the accessory chain is part of the grounding, not an accessory to it." },
 { step: "Decide dry, wet or immersion", detail: "Coolant-wet swarf wants recovery designed for liquid. Reactive fines may warrant immersion separation so material stays wetted." },
 { step: "Set a frequency and record it", detail: "Grinding areas accumulate fast. Defined intervals for defined surfaces, logged, is what makes the programme defensible." },
 ],
 setupNote: {
 text: "Recovering grinding dust is housekeeping, not source capture. If dust is escaping while the grinder runs, that is a ducted collection question and a different piece of equipment — ",
 link: { label: "the difference is worth understanding", href: "/guides/vacuum-vs-dust-collector" },
 textAfter: " before buying either.",
 },
 faqs: [
 {
 question: "Is grinding dust combustible?",
 answer:
 "The metal fraction generally is. Grinding reduces metal to fine, freshly exposed particles with a large surface area, and that behaves as a combustible dust — with aluminium, magnesium and titanium fines being genuinely reactive. The abrasive fraction shed from the wheel is mineral and does not burn. Since grinding also produces sparks, the same operation supplies both fuel and ignition, which is why accumulation control matters so much in these areas.",
 },
 {
 question: "Can I use a shop vacuum for grinding dust?",
 answer:
 "No. A shop vacuum has a brushed motor that sparks in normal operation, a plastic hose that accumulates static as dry fines pass through it, and filtration that returns the finest fraction to the room — three problems in an area that already contains an active ignition source. It will also degrade quickly, because grinding debris is abrasive.",
 },
 {
 question: "Do I need a grinding dust collector or a vacuum?",
 answer:
 "They do different jobs. A dust collector captures dust at the source through ducted hoods while the grinder runs; a vacuum removes what has already settled on machines, benches, floors and overhead surfaces. Most grinding areas benefit from both, and PrestiVac builds the vacuum half — we do not manufacture dust collectors, and we would rather say so than sell you the wrong equipment.",
 },
 {
 question: "What about stainless steel grinding specifically?",
 answer:
 "Stainless grinding and welding raise hexavalent chromium as an exposure concern, which OSHA addresses under 29 CFR 1910.1026. That makes retained HEPA filtration and contained disposal part of the specification rather than an upgrade, alongside the general combustible metal dust considerations that apply to the fines themselves.",
 },
 ],
 relatedApplications: [
 "deburring",
 "welding-cleanup",
 "cnc-machining",
 "sanding",
 "thermal-spray",
 "conveyor-housekeeping",
 ],
 relatedResources: [
 { label: "Explosion Proof Vacuums", href: "/products/explosion-proof-vacuums" },
 { label: "Explosion-Proof Vacuum Guide", href: "/resources/explosion-proof-vacuum-guide" },
 { label: "Combustible Dust Solutions", href: "/resources/combustible-dust-solutions" },
 { label: "The NFPA Landscape", href: "/resources/nfpa-guide" },
 ],
};
