import { AlertTriangle, Filter, ScrollText, ShieldCheck } from "lucide-react";

import type { MaterialGuideData } from "@/components/templates/material-guide";

export const berylliumDustGuide: MaterialGuideData = {
 slug: "beryllium-dust",
 name: "Beryllium Dust",
 groupCrumb: { label: "Metal Dusts", anchor: "metal-dusts" },
 seo: {
 title: "Is Beryllium Toxic? Beryllium Dust Hazards & Safe Recovery",
 description:
 "Beryllium is acutely hazardous at extremely low airborne concentrations and has its own OSHA standard. Chronic beryllium disease, sensitisation, where exposure arises, and why HEPA recovery replaces sweeping entirely.",
 },
 heroIntro:
 "Built for one of the most exposure-sensitive metals in industry. Beryllium causes an irreversible immune-mediated lung disease in susceptible people at airborne concentrations orders of magnitude below ordinary dust limits — which is why it carries its own OSHA standard and why dry cleaning methods are simply not on the table.",
 badges: [
 { icon: AlertTriangle, title: "Extremely Low Limits", detail: "OSHA beryllium standard 29 CFR 1910.1024" },
 { icon: Filter, title: "HEPA Filtration", detail: "Tested 99.99% at 0.3 um" },
 { icon: ScrollText, title: "Medical Surveillance", detail: "Sensitisation screening under the standard" },
 { icon: ShieldCheck, title: "Contained Recovery", detail: "Sealed disposal; no sweeping, no blowdown" },
 ],
 facts: [
 { label: "Material type", value: "Toxic light metal - dust, fume, mist and soluble compounds" },
 { label: "Primary hazard", value: "Chronic beryllium disease and sensitisation; classified carcinogenic to humans by IARC" },
 { label: "Distinguishing feature", value: "Hazardous at airborne concentrations far below general dust limits" },
 { label: "Governing standard", value: "OSHA beryllium standard, 29 CFR 1910.1024" },
 ],
 overview: [
 "Beryllium is unusual in that a genuinely tiny exposure can matter. In susceptible individuals it provokes an immune response - beryllium sensitisation - which can progress to chronic beryllium disease, a granulomatous lung condition that is irreversible and can be disabling. Because susceptibility is immunological rather than dose-linear in the ordinary sense, the protective strategy is to keep airborne beryllium as close to absent as achievable rather than merely below a threshold.",
 "Exposure arises wherever beryllium-containing material is machined, ground, abraded, melted or welded. Copper-beryllium alloys are the most widespread source and appear in springs, connectors, non-sparking tools, moulds and aerospace components; beryllium also appears in some ceramics, in foundry operations and in dental and electronics work. Because the material is often present as a few percent of an alloy, the hazard frequently travels unrecognised under a part description that says nothing about beryllium at all. OSHA regulates it under a dedicated standard, 29 CFR 1910.1024, which brings exposure assessment, regulated areas, medical surveillance for sensitisation, and housekeeping provisions that rule out dry methods.",
 ],
 industries: [
 { label: "Aerospace & Defense", href: "/industries/aerospace" },
 { label: "Metalworking & Machining", href: "/industries/metalworking" },
 { label: "Foundry", href: "/industries/foundry" },
 { label: "Electronics", href: "/industries/electronics" },
 { label: "Medical Devices", href: "/industries/medical-devices" },
 ],
 riskHeading: "Why beryllium demands a different standard of care",
 risks: [
 "Immune-mediated disease: beryllium sensitisation can progress to chronic beryllium disease, which is irreversible - the mechanism is immunological, so susceptibility varies between individuals.",
 "Hazardous at minute concentrations: the airborne levels of concern sit far below general dust limits, making operator perception useless as a control.",
 "Classified carcinogen: beryllium and beryllium compounds are classified as carcinogenic to humans by IARC, adding a long-latency risk to the respiratory one.",
 "Hidden in alloys: copper-beryllium is often a small percentage of an alloy, so machining a part that nobody described as beryllium can still generate exposure.",
 "Persistent contamination: beryllium dust settles on surfaces, tools and clothing and stays there - which is why the standard addresses regulated areas and hygiene as well as air.",
 "Generated by ordinary operations: grinding, sanding, sawing, deburring and welding all produce respirable particulate from solid stock that is otherwise inert to handle.",
 ],
 solutions: [
 "HEPA-filtered vacuum recovery tested to 99.99% at 0.3 um as the standard cleaning method, with no dry sweeping and no compressed-air blowdown anywhere in the area.",
 "Source capture at machining, grinding and deburring stations so particulate is collected as it is generated rather than after it has settled and spread.",
 "Sealed collection and disposal handled as regulated waste, with the container change treated as a controlled procedure.",
 "Dedicated, labelled equipment that never leaves the regulated area, preventing transfer into clean parts of the facility.",
 "Wet methods where the process and the exposure assessment support them, reducing airborne generation at the point of work.",
 "Documented cleaning frequencies forming part of the written compliance programme rather than informal practice.",
 ],
 configuration: [
 { step: "Establish whether beryllium is present", detail: "Confirm alloy composition with suppliers. Copper-beryllium is frequently unlabelled in shop practice, and the exposure assessment cannot start until presence is known." },
 { step: "Work to the exposure assessment", detail: "OSHA's beryllium standard drives controls from measured exposure. Equipment selection follows that assessment rather than preceding it." },
 { step: "Specify tested HEPA retention", detail: "Ask what the filtration is tested to. For a substance at these concentrations, retained filtration is the whole point of the machine." },
 { step: "Design the disposal step", detail: "Sealed liners, a defined route out, and a procedure for the container change - the moment of highest potential exposure in the whole cycle." },
 { step: "Dedicate and label equipment", detail: "Keep vacuums, hoses and accessories inside the regulated area so beryllium does not migrate on shared tooling." },
 ],
 bestPractices: [
 "Verify alloy composition before machining unfamiliar stock - beryllium content is often invisible in a part description.",
 "Never sweep or blow down a beryllium area; both re-suspend a substance that is hazardous at minute concentrations.",
 "Keep beryllium equipment dedicated, labelled and inside the regulated area at all times.",
 "Treat filter and container changes as controlled procedures with the protection the exposure assessment specifies.",
 "Include beryllium surfaces in scheduled cleaning with defined intervals rather than cleaning when they look dirty.",
 "Support the medical surveillance provisions of the standard - sensitisation screening exists because early detection matters.",
 ],
 faqs: [
 {
 question: "Is beryllium toxic?",
 answer:
 "Yes, and it is toxic at remarkably low airborne concentrations. In susceptible people beryllium provokes an immune response called sensitisation, which can progress to chronic beryllium disease - an irreversible granulomatous lung condition. Beryllium and its compounds are also classified as carcinogenic to humans by IARC. OSHA regulates it under a dedicated standard, 29 CFR 1910.1024, with exposure limits far below those for ordinary dusts.",
 },
 {
 question: "Where does beryllium dust come from?",
 answer:
 "Machining, grinding, sanding, sawing, deburring, melting and welding beryllium-containing material. Copper-beryllium alloys are the most common source and appear in springs, electrical connectors, non-sparking tools, moulds and aerospace parts. Because beryllium is often only a small percentage of the alloy, exposure frequently occurs during work nobody flagged as beryllium work.",
 },
 {
 question: "Can beryllium dust be swept up?",
 answer:
 "No. Dry sweeping and compressed-air blowdown re-suspend particulate that is hazardous at minute concentrations, and where the OSHA beryllium standard applies they are not acceptable cleaning methods. HEPA-filtered vacuum recovery with sealed disposal, and wet methods where appropriate, are the expected controls.",
 },
 {
 question: "Is beryllium dust combustible?",
 answer:
 "Finely divided beryllium is assessed as a combustible metal dust and should be tested rather than assumed. But the reason beryllium is controlled so tightly is toxicological, not a deflagration concern - the exposure limits, not the fire risk, are what dictate how you clean.",
 },
 ],
 recommended: ["hepa-vacuums", "explosion-proof-vacuums", "custom-engineered-systems", "accessories"],
 related: [
   { label: "Research laboratory case study", href: "/case-studies/beryllium-dust-national-laboratory" },
 { label: "Explosion proof vacuums", href: "/products/explosion-proof-vacuums" },
 { label: "Cadmium Dust guide", href: "/materials/cadmium-dust" },
 { label: "Lead Dust guide", href: "/materials/lead-dust" },
 { label: "Aerospace deep dive", href: "/industries/aerospace" },
 { label: "Class II Groups E, F & G", href: "/hazardous-locations/class-ii-groups-e-f-g" },
 ],
};
