import { Filter, Flame, Leaf, ShieldCheck } from "lucide-react";

import type { MaterialGuideData } from "@/components/templates/material-guide";

export const pelletDustGuide: MaterialGuideData = {
 slug: "pellet-dust",
 name: "Pellet Dust",
 groupCrumb: { label: "Biomass & Renewable Energy Dusts", anchor: "biomass-dusts" },
 seo: {
  title: "Pellet Dust — Combustible Dust Control",
  description:
   "Wood and biomass pellet handling generates fines through attrition at every transfer, and pellet fines are finer and drier than the material they came from.",
 },
 heroIntro:
  "Built for pellet production, storage and handling, where the dust is created by the pellets rubbing against each other and everything else. Pellet fines are drier and finer than the feedstock they were made from, which makes them more readily dispersed, not less.",
 badges: [
 { icon: ShieldCheck, title: "Explosion-Safe Design", detail: "Grounded, bonded, conductive recovery path" },
 { icon: Leaf, title: "Attrition-Generated Fines", detail: "Dust is created at every transfer point" },
 { icon: Flame, title: "Self-Heating in Storage", detail: "Documented in pellet silos and bulk storage" },
 { icon: Filter, title: "HEPA Filtration", detail: "Tested 99.99% at 0.3 um" },
 ],
 facts: [
 { label: "Material type", value: "Combustible organic dust, Class II Group G (non-conductive)" },
 { label: "Where it is generated", value: "Pelletising, cooling, screening, conveying, silo loading, ship and rail loadout, and end-user handling" },
 { label: "Distinguishing property", value: "Fines are generated continuously by attrition and are drier and finer than the original feedstock" },
 { label: "Governing standards", value: "NFPA 660, consolidating the former wood and particulate standards" },
 ],
 overview: [
 "Pellets are made specifically to be dense, dry and handleable, and that is exactly why they generate dust. Every transfer — conveyor to conveyor, into silos, into ships and rail cars, into end-user hoppers — abrades pellet surfaces against each other, producing fines continuously. A handling chain with many transfer points produces more dust than one with few, regardless of how well any individual point is enclosed.",
 "Those fines are drier and finer than the feedstock the pellets were made from, because pelletising involves drying and compression. That makes them more readily dispersed than the original material, and it means an operation that handled green feedstock without a serious dust problem can find that pelletising has created one. Bulk pellet storage also carries a documented self-heating record, and off-gassing in enclosed pellet storage is a recognised confined-space hazard in this sector.",
 ],
 industries: [
 { label: "Energy & Power", href: "/industries/energy" },
 { label: "Woodworking", href: "/industries/woodworking" },
 { label: "Agriculture & Grain", href: "/industries/agriculture" },
 { label: "Marine & Shipyard", href: "/industries/marine" },
 { label: "Rail", href: "/industries/rail" },
 ],
 riskHeading: "What makes pellet dust worth controlling",
 risks: [
 "Attrition at every transfer: fines are generated continuously by pellets abrading against each other and against equipment.",
 "Drier and finer than feedstock: pelletising dries and compresses, so the resulting fines disperse more readily than the original material.",
 "Transfer point multiplication: each additional handling step in the chain adds to the total dust generated.",
 "Self-heating in bulk storage: documented in pellet silos, requiring monitoring independent of housekeeping.",
 "Off-gassing: enclosed pellet storage can release gases, making silo entry a confined-space question.",
 "Loadout releases: ship and rail loading move large tonnages quickly and are typically the least enclosed points.",
 ],
 solutions: [
 "Recovery sized against the number of transfer points, since attrition generates fines at each one.",
 "Storage monitoring for self-heating in bulk pellet silos.",
 "Explosion-proof construction across pelletising, cooling, screening and loadout.",
 "Confined-space procedure for pellet storage entry, given off-gassing behaviour.",
 "Grounded, bonded conductive path through conveying and ship or rail loading.",
 "HEPA-filtered collection retaining a fraction drier and finer than the original feedstock.",
 ],
 configuration: [
 { step: "Count the transfer points", detail: "Fines are generated by pellets abrading at each handover, so dust load tracks handling steps as much as tonnage." },
 { step: "Expect finer material than the feedstock", detail: "Pelletising dries and compresses, so the resulting fines disperse more readily than the raw material did." },
 { step: "Confirm the classification", detail: "Your engineer assigns the classification for pelletising and loadout areas." },
 { step: "Monitor bulk storage", detail: "Self-heating in pellet silos is documented and requires no ignition source." },
 { step: "Plan loadout separately", detail: "Ship and rail loading move large tonnages quickly and are typically least enclosed." },
 ],
 bestPractices: [
 "Reduce or enclose transfer points where possible — each one makes dust.",
 "Do not assume pellet fines behave like the wood they came from; they are drier and finer.",
 "Monitor silos for self-heating.",
 "Treat storage entry as confined-space work.",
 "Prioritise loadout, the least enclosed point in most chains.",
 "Empty into sealed disposal away from storage.",
 ],
 faqs: [
 {
  question: "Where does pellet dust actually come from?",
  answer:
   "Attrition. Pellets rubbing against each other and against equipment at every transfer point produce fines continuously. That means the dust load tracks the number of handling steps in the chain as much as the tonnage moved.",
 },
 {
  question: "Are pellet fines worse than the original wood dust?",
  answer:
   "More readily dispersed, generally. Pelletising involves drying and compression, so the fines that come off are drier and finer than the feedstock the pellets were made from. An operation that handled green material without difficulty can find pelletising has created a dust problem.",
 },
 {
  question: "Do pellet silos self-heat?",
  answer:
   "Bulk pellet storage carries a documented self-heating record, and it needs no external ignition source. Storage monitoring belongs alongside the housekeeping programme rather than being treated as a separate concern.",
 },
 {
  question: "Is entry into pellet storage a hazard?",
  answer:
   "Enclosed pellet storage can off-gas, which is a recognised confined-space hazard in this sector. Silo and bunker entry should go through your confined-space procedure rather than being treated as routine.",
 },
 ],
 recommended: ["explosion-proof-vacuums", "hepa-vacuums", "pneumatic-vacuums", "industrial-vacuums"],
 related: [
 { label: "Biomass Dust guide", href: "/materials/biomass-dust" },
 { label: "Sawdust guide", href: "/materials/sawdust" },
 { label: "Wood Dust guide", href: "/materials/wood-dust" },
 { label: "Energy & Power deep dive", href: "/industries/energy" },
 { label: "Woodworking deep dive", href: "/industries/woodworking" },
 ],
};
