import { Filter, ShieldCheck, Wind, Zap } from "lucide-react";

import type { MaterialGuideData } from "@/components/templates/material-guide";

export const sulfurDustGuide: MaterialGuideData = {
 slug: "sulfur-dust",
 name: "Sulfur Dust",
 groupCrumb: { label: "Chemical Dusts", anchor: "chemical-dusts" },
 seo: {
 title: "Sulfur Dust Vacuum Solutions",
 description:
 "Sulfur has the lowest ignition energy of any common industrial dust and its own legacy NFPA standard (655, now in NFPA 660). How sulfur fines are safely collected: verified grounding, air-operated explosion-proof recovery, SO2-aware disposal.",
 },
 heroIntro:
 "Built for the most ignition-sensitive common industrial dust — where a static discharge too weak to feel can be enough, grounding leads the program rather than appearing in it, and even the disposal path is designed around what sulfur becomes when it burns.",
 badges: [
 { icon: ShieldCheck, title: "Explosion-Safe Design", detail: "Engineered to NFPA 655 / 660 practice" },
 { icon: Zap, title: "Static Control", detail: "The governing control for sulfur" },
 { icon: Wind, title: "Air-Operated Options", detail: "Zero electrical components" },
 { icon: Filter, title: "HEPA Filtration", detail: "Fines retained — 99.99% at 0.3 µm" },
 ],
 facts: [
 { label: "Material type", value: "Combustible inorganic element — milled powder and prill fines" },
 { label: "Ignition sensitivity", value: "Among the lowest ignition energies of common industrial dusts — static discharges too weak to feel can suffice" },
 { label: "Combustion product", value: "Sulfur dioxide (SO2), a toxic gas — even a small fire is a gas event" },
 { label: "Governing standards", value: "NFPA 655, consolidated into NFPA 660; NFPA 652 DHA baseline" },
 ],
 overview: [
 "Sulfur occupies a singular position in the combustible dust catalog. It is one of the few materials with its own dedicated NFPA standard — NFPA 655, Prevention of Sulfur Fires and Explosions, now carried into the consolidated NFPA 660 — and its minimum ignition energy is among the lowest reported for any common industrial dust: of the same order as the static discharges generated by ordinary powder handling, and below what a person can reliably feel. Controls that are adequate for ordinary dusts leave sulfur exposed; for this material, static control is not a line in the program — it is the program.",
 "Sulfur is handled dry wherever it is used — vulcanizing rubber, feeding agrochemical and pigment formulations — as milled powder and prilled granules whose handling abrades a fine fraction free. The engineered response holds three facts at once: charge must have nowhere to accumulate (bonded, conductive, verified equipment end to end), the recovery path must offer no ignition source of its own (air-operated units answer that categorically), and collected sulfur must move promptly in sealed, conductive, oxidizer-segregated containers — because sulfur that ignites burns to sulfur dioxide, making the disposal path a safety system in its own right.",
 ],
 industries: [
 { label: "Chemical Processing", href: "/industries/chemical" },
 { label: "Agriculture & Agrochemicals", href: "/industries/agriculture" },
 { label: "Plastics & Rubber", href: "/industries#plastics-rubber" },
 { label: "Oil & Gas", href: "/industries#oil-gas" },
 { label: "Powder Blending", href: "/applications#chemical-processing" },
 { label: "Packaging Lines", href: "/applications#chemical-processing" },
 ],
 riskHeading: "Explosion & fire risks",
 risks: [
 "Ignition energy among the lowest of any industrial dust — ordinary static discharges, including ones too weak to notice, can exceed it",
 "Isolated conductors in the transfer chain — plastic scoops, liners, ungrounded drums — store charge silently and deliver it as a single spark",
 "Burning sulfur produces sulfur dioxide, a toxic gas — even a contained smolder is an evacuation-scale event",
 "Settled fines on surrounds, cable trays and ledges fuel secondary events — the mechanism the housekeeping standards target",
 "Solvent vapors nearby form hybrid mixtures that ignite even more easily than the dust alone",
 ],
 solutions: [
 "Grounding architecture first: bonded transfer points with verification — continuity checked before use and re-verified on PM",
 "Air-operated explosion-proof vacuums — no motor, no switchgear, no electrical components anywhere on the unit",
 "Static-dissipative hoses with grounded stainless tools: a continuous conductive path from pickup to canister",
 "Sealed conductive containers, grounded during transfer, segregated from oxidizers, dispositioned promptly per the SDS",
 "Tested HEPA final-stage filtration — fines retained rather than redistributed during cleaning",
 ],
 configuration: [
 { step: "Collection tool", detail: "Grounded stainless wand or nozzle at the source" },
 { step: "Static-dissipative hose", detail: "Conductive path, bonded end to end" },
 { step: "Air-operated EX unit", detail: "Zero electrical components near the material" },
 { step: "HEPA final stage", detail: "Tested 99.99% at 0.3 µm — fines stay captured" },
 { step: "Sealed conductive container", detail: "Grounded transfer; oxidizer-segregated, prompt disposition" },
 ],
 bestPractices: [
 "Verify grounding continuity before every use — for sulfur, the ground strap is the safety system",
 "Hunt isolated conductors: no plastic scoops, no insulating liners, no ungrounded drums in the transfer chain",
 "Never sweep or blow down sulfur fines — vacuum capture only, at the source",
 "No standing inventory: collected sulfur moves promptly, sealed and segregated from oxidizers",
 "Treat solvent-adjacent areas with the full process-area discipline — hybrid mixtures lower the bar further",
 ],
 faqs: [
 {
 question: "Is sulfur flammable?",
 answer:
 "Yes. Elemental sulfur is combustible and burns with a pale blue flame, producing sulfur dioxide — an acutely irritating toxic gas that makes the atmosphere after a sulfur fire hazardous in its own right. As a fine powder sulfur is among the more ignition-sensitive industrial dusts, which is why handling areas are kept clean rather than merely tidy.",
 },
 {
 question: "Is sulfur dust explosive?",
 answer:
 "Suspended sulfur dust in a confined space can deflagrate, and sulfur is recognised for igniting from relatively weak energy sources — including static discharge. That combination of easy ignition and a toxic combustion product is what drives grounded, bonded, conductive recovery equipment in sulfur handling areas rather than ordinary industrial vacuums.",
 },
 {
 question: "Is sulphur flammable? (British spelling)",
 answer:
 "Same material, same answer: sulphur and sulfur are spelling variants of the same element, and it is combustible in both. Fine sulphur powder is treated as a combustible dust, and its combustion produces sulfur dioxide.",
 },
 {
 question: "Why does static control lead the sulfur program?",
 answer:
 "Because reported ignition energies for fine sulfur sit at or below the energy of static discharges a person can't even feel. When the ignition threshold is that low, the only robust posture is denying charge anywhere to accumulate — bonding, conductive materials and verified continuity convert static from a managed risk into an engineered-out one.",
 },
 {
 question: "Electric explosion-proof or air-operated for sulfur rooms?",
 answer:
 "Both can be legitimate, but air-operated units answer the question categorically: no motor, no switch, no electrical component anywhere on the vacuum. For the most ignition-sensitive rooms, removing the question outranks answering it — and conductive construction drains operating charge to verified ground continuously.",
 },
 {
 question: "Is prilled sulfur safer than milled powder?",
 answer:
 "Coarse prills are less dispersible, but handling abrades a fine fraction free — and the fines govern the hazard. Specify the program for the dust the process actually creates, not the granule size on the purchase order.",
 },
 {
 question: "How should collected sulfur be handled?",
 answer:
 "As a toxic-gas precursor as well as a fuel: sealed conductive containers that limit air to any incipient smolder, grounding during every transfer, segregation from oxidizer storage per the SDS, and prompt disposition so no inventory stands waiting.",
 },
 ],
 studySlug: "sulfur-dust-specialty-chemical-plant",
 recommended: ["explosion-proof-vacuums", "pneumatic-vacuums", "hepa-vacuums", "accessories"],
 related: [
 { label: "Explosion proof vacuums", href: "/products/explosion-proof-vacuums" },
 { label: "Combustible dust classification", href: "/hazardous-locations/combustible-dust-classification" },
 { label: "Carbon Black guide", href: "/materials/carbon-black" },
 { label: "Chemical Processing deep dive", href: "/industries/chemical" },
 { label: "Explosion Proof Vacuum Guide", href: "/resources/explosion-proof-vacuum-guide" },
 { label: "The NFPA Landscape", href: "/resources/nfpa-guide" },
 ],
};
