import { NextResponse } from "next/server";

import { resendConfigured, sendAcknowledgement, sendNotification } from "@/lib/email";

/**
 * Quote request endpoint.
 *
 * Quote requests are delivered to prestivac@gmail.com.
 *
 * Two delivery paths, in priority order:
 *   1. QUOTE_WEBHOOK_URL — any HTTPS endpoint (CRM intake, Zapier, Make, n8n)
 *      configured to forward to prestivac@gmail.com. Preferred, because it is
 *      trackable as a conversion.
 *   2. Mail fallback — if no webhook is configured the form composes a
 *      pre-filled message to info@prestivac.com containing every field and the
 *      reference number, so no enquiry is ever silently dropped.
 *
 * If nothing is configured the route returns 503 with `configured: false`, and
 * the form falls back to a pre-filled mail draft so a lead is never silently
 * dropped. That fallback is deliberate: a form that appears to submit and
 * discards the enquiry is worse than no form at all.
 */

export type QuotePayload = {
  name: string;
  company: string;
  email: string;
  phone?: string;
  material?: string;
  classification?: string;
  application?: string;
  quantity?: string;
  source?: string;
  /** Customer-facing reference generated by the form. */
  reference?: string;
};

function isValid(body: Partial<QuotePayload>): body is QuotePayload {
  return Boolean(
    body.name?.trim() &&
      body.company?.trim() &&
      body.email?.trim() &&
      /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(body.email.trim()),
  );
}

const LABELS: Record<string, string> = {"name": "Name", "company": "Company", "email": "Email", "phone": "Phone", "address": "Address", "cityState": "City / State", "zip": "ZIP", "products": "Products to vacuum", "explosive": "Explosive atmosphere", "toxic": "Toxic material", "classification": "Area classification", "operation": "Operation", "capacity": "Capacity", "compressedAir": "Compressed air", "voltage": "Voltage", "filtration": "Filtration", "hose": "Hose", "accessories": "Accessories", "additional": "Additional detail", "source": "Submitted from"};

export async function POST(request: Request) {
  let body: Partial<QuotePayload>;
  try {
    body = (await request.json()) as Partial<QuotePayload>;
  } catch {
    return NextResponse.json({ ok: false, error: "invalid_json" }, { status: 400 });
  }

  if (!isValid(body)) {
    return NextResponse.json(
      { ok: false, error: "missing_required_fields" },
      { status: 422 },
    );
  }

  // Delivery path 1 — Resend. Preferred: it sends real email, needs no third-party
  // automation, and lets us acknowledge to the customer as well.
  if (resendConfigured()) {
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const { name, email, reference: _ref, ...rest } = body;
    // The form always supplies a reference. Fall back to a server-side one rather
    // than sending an unidentifiable enquiry if a client ever omits it.
    const reference = body.reference?.trim() || `PV-Q-${new Date().toISOString().slice(0,10).replace(/-/g,"")}-SRV`;
    const result = await sendNotification({
      kind: "Quote request",
      reference,
      fields: { name, email, ...rest },
      labels: LABELS,
      replyTo: email,
    });

    if (!result.ok) {
      return NextResponse.json(
        { ok: false, configured: true, error: result.message },
        { status: 502 },
      );
    }

    // Best effort — the enquiry has already been delivered, so a failed
    // acknowledgement must not fail the submission.
    if (email) {
      const ack = await sendAcknowledgement({ to: email, name, reference, kind: "Quote request" });
      if (!ack.ok) console.warn("Acknowledgement email failed:", ack.message);
    }

    return NextResponse.json({ ok: true, reference });
  }

  const webhook = process.env.QUOTE_WEBHOOK_URL;
  if (!webhook) {
    return NextResponse.json(
      {
        ok: false,
        configured: false,
        error: "delivery_not_configured",
        message:
          "Webhook delivery is not configured; the form falls back to emailing prestivac@gmail.com. Set QUOTE_WEBHOOK_URL to enable tracked delivery.",
      },
      { status: 503 },
    );
  }

  try {
    const response = await fetch(webhook, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ ...body, receivedAt: new Date().toISOString() }),
    });
    if (!response.ok) {
      return NextResponse.json(
        { ok: false, error: "delivery_failed", status: response.status },
        { status: 502 },
      );
    }
    return NextResponse.json({ ok: true, reference: body.reference });
  } catch {
    return NextResponse.json({ ok: false, error: "delivery_error" }, { status: 502 });
  }
}
