import { NextResponse } from "next/server";

/**
 * Quote request endpoint.
 *
 * Quote requests are delivered to info@prestivac.com.
 *
 * Two delivery paths, in priority order:
 *   1. QUOTE_WEBHOOK_URL — any HTTPS endpoint (CRM intake, Zapier, Make, n8n)
 *      configured to forward to info@prestivac.com. Preferred, because it is
 *      trackable as a conversion.
 *   2. Mail fallback — if no webhook is configured the form composes a
 *      pre-filled message to info@prestivac.com containing every field and the
 *      reference number, so no enquiry is ever silently dropped.
 *
 * If nothing is configured the route returns 503 with `configured: false`, and
 * the form falls back to a pre-filled mail draft so a lead is never silently
 * dropped. That fallback is deliberate: a form that appears to submit and
 * discards the enquiry is worse than no form at all.
 */

export type QuotePayload = {
  name: string;
  company: string;
  email: string;
  phone?: string;
  material?: string;
  classification?: string;
  application?: string;
  quantity?: string;
  source?: string;
  /** Customer-facing reference generated by the form. */
  reference?: string;
};

function isValid(body: Partial<QuotePayload>): body is QuotePayload {
  return Boolean(
    body.name?.trim() &&
      body.company?.trim() &&
      body.email?.trim() &&
      /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(body.email.trim()),
  );
}

export async function POST(request: Request) {
  let body: Partial<QuotePayload>;
  try {
    body = (await request.json()) as Partial<QuotePayload>;
  } catch {
    return NextResponse.json({ ok: false, error: "invalid_json" }, { status: 400 });
  }

  if (!isValid(body)) {
    return NextResponse.json(
      { ok: false, error: "missing_required_fields" },
      { status: 422 },
    );
  }

  const webhook = process.env.QUOTE_WEBHOOK_URL;
  if (!webhook) {
    return NextResponse.json(
      {
        ok: false,
        configured: false,
        error: "delivery_not_configured",
        message:
          "Webhook delivery is not configured; the form falls back to emailing info@prestivac.com. Set QUOTE_WEBHOOK_URL to enable tracked delivery.",
      },
      { status: 503 },
    );
  }

  try {
    const response = await fetch(webhook, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ ...body, receivedAt: new Date().toISOString() }),
    });
    if (!response.ok) {
      return NextResponse.json(
        { ok: false, error: "delivery_failed", status: response.status },
        { status: 502 },
      );
    }
    return NextResponse.json({ ok: true, reference: body.reference });
  } catch {
    return NextResponse.json({ ok: false, error: "delivery_error" }, { status: 502 });
  }
}
