import type { MetadataRoute } from "next";

import { CASE_STUDY_LIBRARY } from "@/lib/data/case-study-library";
import { GUIDE_ARTICLES } from "@/lib/data/guides";
import { HAZARDOUS_LOCATION_TOPICS } from "@/lib/data/hazardous-locations";
import { PRODUCT_CATEGORIES } from "@/lib/data/product-categories";
import { FR_APPLICATIONS } from "@/lib/data/fr-applications";
import { FR_MATERIALS } from "@/lib/data/fr-materials";
import { RESOURCES } from "@/lib/data/resources";
import { ALL_MODELS } from "@/lib/data/product-models";
import { site } from "@/lib/site";

export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date();
  const staticRoutes: MetadataRoute.Sitemap = [
    { url: site.url, lastModified, changeFrequency: "weekly", priority: 1 },
    { url: site.url + "/products", lastModified, changeFrequency: "monthly", priority: 0.8 },
    { url: site.url + "/applications", lastModified, changeFrequency: "monthly", priority: 0.8 },
    { url: site.url + "/applications/cnc-machining", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/applications/metal-3d-printing", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/applications/powder-coating", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/applications/silo-cleaning", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/applications/welding-cleanup", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/applications/warehouse-housekeeping", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/applications/dust-collector-cleaning", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/applications/spill-cleanup", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/applications/abrasive-blasting", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/applications/deburring", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/applications/mixing-blending", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/applications/tank-cleaning", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/applications/bagging-dumping", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/applications/thermal-spray", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/applications/conveyor-housekeeping", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/applications/drum-filling", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/applications/sanding", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries", lastModified, changeFrequency: "monthly", priority: 0.8 },
    { url: site.url + "/industries/pharmaceutical", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries/battery", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries/food-beverage", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries/agriculture", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries/woodworking", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries/automotive", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries/aerospace", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries/metalworking", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries/chemical", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries/coal", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries/data-centers", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries/foundry", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries/abatement", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries/ammunition", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries/electronics", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries/cleanrooms", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries/cosmetics", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries/education", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries/biotech", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries/recycling", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries/medical-devices", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries/mining", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries/oil-gas", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries/additive-manufacturing", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries/glass-ceramics", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries/paints-coatings", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries/cannabis", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries/hydrogen", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries/textile", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries/marine", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries/rail", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries/paper-mills", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries/printing", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries/vacuum-furnace", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries/construction-materials", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries/plastics-rubber", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries/energy", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/industries/paper-packaging", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials", lastModified, changeFrequency: "monthly", priority: 0.8 },
    { url: site.url + "/materials/aluminum-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/titanium-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/graphite-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/wood-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/magnesium-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/sulfur-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/carbon-black", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/flour-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/grain-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/starch-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/vermiculite-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/tea-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/calcium-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/applications/grinding-dust", lastModified, changeFrequency: "monthly", priority: 0.75 },
    { url: site.url + "/applications/cleanroom-vacuuming", lastModified, changeFrequency: "monthly", priority: 0.75 },
    { url: site.url + "/materials/cadmium-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/beryllium-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/arsenic-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/brass-bronze-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/malt-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/combustible-metal-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/sugar-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/corn-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/cocoa-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/coffee-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/coal-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/coke-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/cotton-wool-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/concrete-cement-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/silica-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/asbestos", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/lead-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/copper-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/plastic-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/zinc-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/nickel-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/cobalt-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/lithium-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/iron-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/chromium-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/zirconium-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/carbon-fiber-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/tin-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/manganese-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/rubber-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/paper-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/leather-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/cork-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/materials/tobacco-dust", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/case-studies", lastModified, changeFrequency: "weekly", priority: 0.8 },
    { url: site.url + "/resources", lastModified, changeFrequency: "monthly", priority: 0.8 },
    { url: site.url + "/about", lastModified, changeFrequency: "monthly", priority: 0.6 },
    { url: site.url + "/faq", lastModified, changeFrequency: "monthly", priority: 0.75 },
    { url: site.url + "/support", lastModified, changeFrequency: "monthly", priority: 0.8 },
    { url: site.url + "/get-a-quote", lastModified, changeFrequency: "monthly", priority: 0.95 },
    { url: site.url + "/fr", lastModified, changeFrequency: "monthly", priority: 0.9 },
    { url: site.url + "/fr/aspirateurs-antideflagrants", lastModified, changeFrequency: "monthly", priority: 0.9 },
    { url: site.url + "/fr/demande-de-soumission", lastModified, changeFrequency: "monthly", priority: 0.85 },
    { url: site.url + "/fr/a-propos", lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: site.url + "/fr/poussieres-et-matieres", lastModified, changeFrequency: "monthly", priority: 0.85 },
    { url: site.url + "/fr/applications", lastModified, changeFrequency: "monthly" as const, priority: 0.85 },
    ...FR_APPLICATIONS.map((a) => ({
      url: site.url + "/fr/applications/" + a.slug,
      lastModified,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    })),
    ...FR_MATERIALS.map((m) => ({
      url: site.url + "/fr/poussieres-et-matieres/" + m.slug,
      lastModified,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    })),
    { url: site.url + "/hazardous-locations", lastModified, changeFrequency: "monthly", priority: 0.85 },
    { url: site.url + "/hazardous-location-vacuums", lastModified, changeFrequency: "monthly", priority: 0.9 },
    { url: site.url + "/combustible-dust", lastModified, changeFrequency: "monthly", priority: 0.9 },
    { url: site.url + "/guides", lastModified, changeFrequency: "monthly", priority: 0.8 },
  ];
  const caseStudies: MetadataRoute.Sitemap = CASE_STUDY_LIBRARY.map((study) => ({
    url: site.url + "/case-studies/" + study.slug,
    lastModified,
    changeFrequency: "monthly",
    priority: 0.7,
  }));
  const productModels: MetadataRoute.Sitemap = ALL_MODELS.map((model) => ({
    url: site.url + "/products/models/" + model.slug,
    lastModified,
    changeFrequency: "monthly",
    priority: 0.6,
  }));
  const productCategories: MetadataRoute.Sitemap = PRODUCT_CATEGORIES.map((category) => ({
    url: site.url + "/products/" + category.slug,
    lastModified,
    changeFrequency: "monthly",
    priority: 0.85,
  }));
  const hazardousLocations: MetadataRoute.Sitemap = HAZARDOUS_LOCATION_TOPICS.map((topic) => ({
    url: site.url + "/hazardous-locations/" + topic.slug,
    lastModified,
    changeFrequency: "monthly",
    priority: 0.8,
  }));
  const guides: MetadataRoute.Sitemap = GUIDE_ARTICLES.map((article) => ({
    url: site.url + "/guides/" + article.slug,
    lastModified,
    changeFrequency: "monthly",
    priority: 0.75,
  }));
  const resourcePages: MetadataRoute.Sitemap = RESOURCES.map((resource) => ({
    url: site.url + "/resources/" + resource.slug,
    lastModified,
    changeFrequency: "monthly",
    priority: 0.8,
  }));
  return [
    ...staticRoutes,
    ...resourcePages,
    ...guides,
    ...caseStudies,
    ...productCategories,
    ...productModels,
    ...hazardousLocations,
  ];
}
