"use client";

import { DirectoryExplorer } from "@/components/directory/directory-explorer";
import { APPLICATION_CATEGORIES } from "@/lib/data/applications";

const FEATURED_ITEM_LINKS: Record<string, string> = {
  "API manufacturing": "/industries/pharmaceutical",
  "Abrasive blasting": "/applications/abrasive-blasting",
  "Air pollution control": "/materials/activated-carbon",
  "Aircraft maintenance": "/industries/aerospace",
  "Aircraft manufacturing": "/industries/aerospace",
  "Aluminum dust collection": "/materials/aluminum-dust",
  "Aluminum machining": "/materials/aluminum-dust",
  "Analytical laboratories": "/industries/education",
  "Anode production": "/materials/graphite-dust",
  "Assembly lines": "/applications/conveyor-housekeeping",
  "Bakery production": "/materials/flour-dust",
  "Battery production": "/industries/battery",
  "Battery recycling": "/materials/battery-black-mass",
  "Beverage production": "/industries/food-beverage",
  "Binder jetting": "/industries/additive-manufacturing",
  "Biomass plants": "/materials/biomass-dust",
  "Bioprocessing": "/industries/biotech",
  "Black mass recovery": "/materials/battery-black-mass",
  "Blender cleaning": "/applications/mixing-blending",
  "Blister packaging": "/industries/pharmaceutical",
  "Blow molding": "/industries/plastics-rubber",
  "Book binding": "/industries/printing",
  "Bottle production": "/industries/plastics-rubber",
  "Brake manufacturing": "/industries/automotive",
  "Brick manufacturing": "/industries/construction-materials",
  "Buffing": "/applications/sanding",
  "Build chamber cleaning": "/applications/metal-3d-printing",
  "Bulk material handling": "/applications/conveyor-housekeeping",
  "CNC grinding": "/applications/grinding-dust",
  "CNC machining": "/applications/cnc-machining",
  "CNC milling": "/applications/cnc-machining",
  "CNC turning": "/applications/cnc-machining",
  "CNC woodworking": "/industries/woodworking",
  "Cabinet making": "/industries/woodworking",
  "Capsule production": "/materials/gelatin-powder",
  "Carbon black vacuuming": "/materials/carbon-black",
  "Cardboard manufacturing": "/materials/corrugated-paper-dust",
  "Catalyst production": "/industries/chemical",
  "Cathode production": "/materials/lithium-dust",
  "Cell assembly": "/industries/battery",
  "Cement plants": "/materials/concrete-cement-dust",
  "Ceramic production": "/industries/glass-ceramics",
  "Cheese production": "/materials/whey-powder",
  "Chemical manufacturing": "/industries/chemical",
  "Chip & coolant separation": "/applications/coolant-recovery",
  "Chip packaging": "/industries/electronics",
  "Chocolate manufacturing": "/materials/cocoa-dust",
  "Classified area cleaning": "/hazardous-locations",
  "Clean assembly": "/applications/cleanroom-vacuuming",
  "Clean laboratories": "/industries/cleanrooms",
  "Cleanroom production": "/applications/cleanroom-vacuuming",
  "Cleanroom vacuuming": "/applications/cleanroom-vacuuming",
  "Cleanrooms": "/industries/cleanrooms",
  "Clinker handling": "/materials/concrete-cement-dust",
  "Coal mining": "/materials/coal-dust",
  "Coffee grinding": "/materials/coffee-dust",
  "Coffee roasting": "/materials/coffee-dust",
  "Combustible dust cleanup": "/combustible-dust",
  "Composite manufacturing": "/materials/carbon-fiber-dust",
  "Compressor stations": "/industries/oil-gas",
  "Concrete plants": "/materials/concrete-cement-dust",
  "Containment rooms": "/products/pharmaceutical-vacuums",
  "Continuous duty vacuuming": "/products/industrial-vacuums",
  "Conveying systems": "/applications/conveyor-housekeeping",
  "Conveyor cleaning": "/applications/conveyor-housekeeping",
  "Conveyor systems": "/applications/conveyor-housekeeping",
  "Corn processing": "/materials/corn-dust",
  "Cotton processing": "/materials/cotton-wool-dust",
  "Crushing plants": "/industries/mining",
  "DMLS printing": "/industries/additive-manufacturing",
  "Dairy production": "/materials/milk-powder",
  "Deburring": "/applications/deburring",
  "Die casting": "/industries/foundry",
  "Display manufacturing": "/industries/electronics",
  "Distribution centers": "/applications/warehouse-housekeeping",
  "Dust collection": "/guides/vacuum-vs-dust-collector",
  "Dust collector cleaning": "/applications/dust-collector-cleaning",
  "Dust recovery": "/combustible-dust",
  "E-waste recycling": "/industries/recycling",
  "EV manufacturing": "/industries/automotive",
  "Electrode manufacturing": "/materials/conductive-carbon",
  "Electronics assembly": "/industries/electronics",
  "Electronics recycling": "/industries/recycling",
  "Engine manufacturing": "/industries/aerospace",
  "Engine plants": "/industries/automotive",
  "Environmental remediation": "/industries/abatement",
  "Extrusion": "/industries/plastics-rubber",
  "Factory housekeeping": "/applications/warehouse-housekeeping",
  "Farm processing": "/industries/agriculture",
  "Feed mills": "/materials/grain-dust",
  "Fermentation": "/industries/biotech",
  "Fertilizer production": "/materials/fertilizer-dust",
  "Fiber processing": "/materials/textile-fibers",
  "Filter cleaning": "/applications/dust-collector-cleaning",
  "Fine powder recovery": "/products/hepa-vacuums",
  "Flexible packaging": "/industries/paper-packaging",
  "Flooring production": "/industries/woodworking",
  "Flour milling": "/materials/flour-dust",
  "Flour mills": "/materials/flour-dust",
  "Fluid bed drying": "/industries/pharmaceutical",
  "Food packaging": "/industries/paper-packaging",
  "Forging": "/industries/metalworking",
  "Foundries": "/industries/foundry",
  "Freeze drying": "/industries/food-beverage",
  "Fuel cells": "/industries/energy",
  "Furnace cleaning": "/industries/vacuum-furnace",
  "Furniture manufacturing": "/industries/woodworking",
  "Garment manufacturing": "/industries/textile",
  "Glass manufacturing": "/industries/glass-ceramics",
  "Glass recycling": "/industries/recycling",
  "Government facilities": "/industries/education",
  "Government labs": "/industries/education",
  "Grain elevators": "/materials/grain-dust",
  "Grain storage": "/applications/silo-cleaning",
  "Granulation": "/industries/pharmaceutical",
  "Graphite handling": "/materials/graphite-dust",
  "Hazardous dust removal": "/hazardous-location-vacuums",
  "Hazardous waste": "/industries/abatement",
  "Heat treating": "/industries/vacuum-furnace",
  "Hopper cleaning": "/applications/silo-cleaning",
  "Hydrogen production": "/industries/hydrogen",
  "Implant manufacturing": "/industries/medical-devices",
  "Injection molding": "/industries/plastics-rubber",
  "Investment casting": "/industries/foundry",
  "Kiln cleaning": "/materials/concrete-cement-dust",
  "LNG terminals": "/industries/oil-gas",
  "Laboratory cleanup": "/industries/biotech",
  "Lamination": "/industries/woodworking",
  "Laser cutting": "/industries/metalworking",
  "Liquid spill cleanup": "/applications/spill-cleanup",
  "Lithium-ion battery production": "/industries/battery",
  "MAP packaging": "/industries/paper-packaging",
  "MDF machining": "/materials/wood-dust",
  "Machine cleaning": "/applications/cnc-machining",
  "Machine shops": "/industries/metalworking",
  "Magnesium dust cleanup": "/materials/magnesium-dust",
  "Material testing": "/industries/education",
  "Meat processing": "/industries/food-beverage",
  "Medical device production": "/industries/medical-devices",
  "Metal 3D printing": "/applications/metal-3d-printing",
  "Metal cutting": "/applications/cnc-machining",
  "Metal fabrication": "/industries/metalworking",
  "Metal recycling": "/materials/combustible-metal-dust",
  "Metal stamping": "/industries/metalworking",
  "Milk powder": "/materials/milk-powder",
  "Mineral processing": "/industries/mining",
  "Mixer cleaning": "/applications/mixing-blending",
  "Module assembly": "/industries/battery",
  "Mold manufacturing": "/industries/metalworking",
  "Molded rubber products": "/industries/plastics-rubber",
  "National laboratories": "/industries/education",
  "Naval facilities": "/industries/marine",
  "Nonwoven production": "/materials/textile-fibers",
  "Nuclear facilities": "/industries/energy",
  "Offshore platforms": "/industries/oil-gas",
  "Oil & coolant recovery": "/applications/coolant-recovery",
  "Ore handling": "/industries/mining",
  "Oven cleaning": "/industries/food-beverage",
  "PCB manufacturing": "/industries/electronics",
  "Packaging": "/industries/paper-packaging",
  "Packaging paper": "/industries/paper-packaging",
  "Paint preparation": "/industries/paints-coatings",
  "Paper mills": "/industries/paper-mills",
  "Pellet production": "/materials/pellet-dust",
  "Pet food": "/materials/grain-dust",
  "Petrochemical plants": "/industries/oil-gas",
  "Pharmaceutical packaging": "/industries/pharmaceutical",
  "Pigment production": "/materials/pigment-dust",
  "Plasma cutting": "/industries/metalworking",
  "Plastic compounding": "/materials/plastic-dust",
  "Plastic packaging": "/materials/plastic-dust",
  "Plastic recycling": "/industries/recycling",
  "Polishing": "/applications/sanding",
  "Polymer 3D printing": "/materials/plastic-dust",
  "Polymer production": "/materials/plastic-dust",
  "Port maintenance": "/industries/marine",
  "Ports": "/industries/marine",
  "Powder blending": "/applications/mixing-blending",
  "Powder coating": "/applications/powder-coating",
  "Powder handling": "/applications/drum-filling",
  "Powder metallurgy": "/materials/combustible-metal-dust",
  "Powder mixing": "/applications/mixing-blending",
  "Powder recovery": "/materials/metal-additive-manufacturing-powder",
  "Powder recycling": "/materials/metal-additive-manufacturing-powder",
  "Powder transfer": "/applications/drum-filling",
  "Power plants": "/materials/coal-dust",
  "Preventive maintenance": "/support",
  "Printer cleaning": "/applications/metal-3d-printing",
  "Printing": "/industries/printing",
  "Production line cleaning": "/applications/conveyor-housekeeping",
  "Rail maintenance": "/industries/rail",
  "Railcar manufacturing": "/industries/rail",
  "Raw meal handling": "/materials/concrete-cement-dust",
  "Reactor cleaning": "/applications/tank-cleaning",
  "Refineries": "/industries/oil-gas",
  "Research laboratories": "/industries/education",
  "Research labs": "/industries/education",
  "Resin production": "/materials/plastic-dust",
  "Resin transfer": "/materials/plastic-dust",
  "Rice milling": "/materials/grain-dust",
  "Robotic welding": "/applications/welding-cleanup",
  "Rotomolding": "/industries/plastics-rubber",
  "Rubber compounding": "/materials/rubber-dust",
  "Rubber recycling": "/materials/rubber-dust",
  "SLM printing": "/industries/additive-manufacturing",
  "SLS printing": "/industries/additive-manufacturing",
  "SMT production": "/industries/electronics",
  "Sanding": "/applications/sanding",
  "Sawmills": "/materials/sawdust",
  "Screening plants": "/industries/mining",
  "Seafood processing": "/industries/food-beverage",
  "Seed plants": "/industries/agriculture",
  "Semiconductor fabrication": "/industries/electronics",
  "Ship repair": "/industries/marine",
  "Shipbuilding": "/industries/marine",
  "Shipping terminals": "/industries/marine",
  "Shot blasting": "/applications/abrasive-blasting",
  "Shutdown cleaning": "/applications/tank-cleaning",
  "Silo cleaning": "/applications/silo-cleaning",
  "Slurry collection": "/products/wet-dry-systems",
  "Snack food production": "/industries/food-beverage",
  "Solar manufacturing": "/industries/energy",
  "Solvent recovery": "/guides/flammable-liquid-recovery",
  "Spice processing": "/materials/spice-dust",
  "Spill cleanup": "/applications/spill-cleanup",
  "Static-safe vacuuming": "/guides/esd-anti-static-vacuums",
  "Sterile packaging": "/industries/medical-devices",
  "Stone fabrication": "/materials/silica-dust",
  "Sugar processing": "/materials/sugar-dust",
  "Surface finishing": "/applications/sanding",
  "Surface preparation": "/applications/abrasive-blasting",
  "Surgical instrument manufacturing": "/industries/medical-devices",
  "Tablet production": "/industries/pharmaceutical",
  "Tank cleaning": "/applications/tank-cleaning",
  "Tank farms": "/applications/tank-cleaning",
  "Textile manufacturing": "/industries/textile",
  "Thermoforming": "/industries/plastics-rubber",
  "Tire manufacturing": "/materials/rubber-dust",
  "Tissue production": "/materials/paper-dust",
  "Titanium dust recovery": "/materials/titanium-dust",
  "Titanium machining": "/materials/titanium-dust",
  "Tool manufacturing": "/industries/metalworking",
  "Transmission manufacturing": "/industries/automotive",
  "Tray sealing": "/industries/paper-packaging",
  "Turbine manufacturing": "/industries/aerospace",
  "Universities": "/industries/education",
  "Vaccine manufacturing": "/industries/biotech",
  "Vacuum coating": "/industries/electronics",
  "Vacuum packaging": "/industries/paper-packaging",
  "Vehicle manufacturing": "/industries/automotive",
  "Veneer production": "/materials/wood-dust",
  "Wafer processing": "/industries/electronics",
  "Warehouse housekeeping": "/applications/warehouse-housekeeping",
  "Warehouses": "/applications/warehouse-housekeeping",
  "Wastewater treatment": "/industries/abatement",
  "Water treatment": "/materials/activated-carbon",
  "Waterjet cutting": "/industries/metalworking",
  "Welding cleanup": "/applications/welding-cleanup",
  "Wheel manufacturing": "/industries/automotive",
  "Wheel shops": "/industries/rail",
  "Wind turbine manufacturing": "/industries/energy",
  "Wood recycling": "/materials/wood-dust",
  "Wood sanding": "/applications/sanding",
};

export function ApplicationsDirectory() {
  return (
    <DirectoryExplorer
      groups={APPLICATION_CATEGORIES}
      featuredLinks={FEATURED_ITEM_LINKS}
      searchLabel="Search the applications directory"
      searchPlaceholder="Search applications — silo cleaning, powder transfer, deburring…"
    />
  );
}
