"use client";

import { DirectoryExplorer } from "@/components/directory/directory-explorer";
import { MATERIAL_GROUPS } from "@/lib/data/materials";

const FEATURED_ITEM_LINKS: Record<string, string> = {
  "Tea dust": "/materials/tea-dust",
  "Calcium metal dust": "/materials/calcium-dust",
  "Vermiculite": "/materials/vermiculite-dust",
  "Cadmium dust": "/materials/cadmium-dust",
  "Beryllium dust": "/materials/beryllium-dust",
  "Arsenic dust": "/materials/arsenic-dust",
  "Combustible metal dust": "/materials/combustible-metal-dust",
  "Malt dust": "/materials/malt-dust",
  "Potato starch": "/materials/starch-dust",
  "Rice starch": "/materials/starch-dust",
  "Wheat starch": "/materials/starch-dust",
  "Aluminum dust": "/materials/aluminum-dust",
  "Titanium dust": "/materials/titanium-dust",
  "Graphite dust": "/materials/graphite-dust",
  "Hardwood dust": "/materials/wood-dust",
  "Softwood dust": "/materials/wood-dust",
  "MDF dust": "/materials/wood-dust",
  "Sawdust": "/materials/wood-dust",
  "Magnesium dust": "/materials/magnesium-dust",
  "Magnesium powder": "/materials/magnesium-dust",
  "Magnesium machining dust": "/materials/magnesium-dust",
  "Sulfur dust": "/materials/sulfur-dust",
  "Carbon black": "/materials/carbon-black",
  "Flour": "/materials/flour-dust",
  "Flour dust": "/materials/flour-dust",
  "Bakery dust": "/materials/flour-dust",
  "Grain dust": "/materials/grain-dust",
  "Wheat dust": "/materials/grain-dust",
  "Feed dust": "/materials/grain-dust",
  "Sugar dust": "/materials/sugar-dust",
  "Powdered sugar": "/materials/sugar-dust",
  "Corn dust": "/materials/corn-dust",
  "Corn starch": "/materials/corn-dust",
  "Cocoa powder": "/materials/cocoa-dust",
  "Chocolate powder": "/materials/cocoa-dust",
  "Coffee dust": "/materials/coffee-dust",
  "Coal dust": "/materials/coal-dust",
  "Coke dust": "/materials/coke-dust",
  "Cotton dust": "/materials/cotton-wool-dust",
  "Cotton lint": "/materials/cotton-wool-dust",
  "Wool dust": "/materials/cotton-wool-dust",
  "Cement kiln dust": "/materials/concrete-cement-dust",
  "Limestone dust": "/materials/concrete-cement-dust",
  "Silica-containing dust": "/materials/silica-dust",
  "Asbestos-containing debris": "/materials/asbestos",
  "Lead dust": "/materials/lead-dust",
  "Copper dust": "/materials/copper-dust",
  "Zinc dust": "/materials/zinc-dust",
  "Zinc powder": "/materials/zinc-dust",
  "Nickel dust": "/materials/nickel-dust",
  "Nickel powder": "/materials/nickel-dust",
  "Nickel alloy powder": "/materials/nickel-dust",
  "Cobalt dust": "/materials/cobalt-dust",
  "Cobalt powder": "/materials/cobalt-dust",
  "Cobalt chrome": "/materials/cobalt-dust",
  "Lithium dust": "/materials/lithium-dust",
  "Lithium metal dust": "/materials/lithium-dust",
  "Iron dust": "/materials/iron-dust",
  "Iron powder": "/materials/iron-dust",
  "Chromium dust": "/materials/chromium-dust",
  "Zirconium dust": "/materials/zirconium-dust",
  "Carbon fiber dust": "/materials/carbon-fiber-dust",
  "Composite material dust": "/materials/carbon-fiber-dust",
  "Copper fines": "/materials/copper-dust",
  "Tin dust": "/materials/tin-dust",
  "Manganese dust": "/materials/manganese-dust",
  "Manganese powder": "/materials/manganese-dust",
  "Plastic powder": "/materials/plastic-dust",
  "Polymer dust": "/materials/plastic-dust",
  "Resin dust": "/materials/plastic-dust",
  "PVC powder": "/materials/plastic-dust",
  "Polyethylene powder": "/materials/plastic-dust",
  "Polypropylene powder": "/materials/plastic-dust",
  "ABS dust": "/materials/plastic-dust",
  "PVC dust": "/materials/plastic-dust",
  "PET dust": "/materials/plastic-dust",
  "Acrylic dust": "/materials/plastic-dust",
  "Polycarbonate dust": "/materials/plastic-dust",
  "Polyurethane dust": "/materials/plastic-dust",
  "Aluminum fines": "/materials/aluminum-dust",
  "Aluminum grinding dust": "/materials/aluminum-dust",
  "Aluminum powder": "/materials/aluminum-dust",
  "Titanium powder": "/materials/titanium-dust",
  "Plywood dust": "/materials/wood-dust",
  "OSB dust": "/materials/wood-dust",
  "Veneer dust": "/materials/wood-dust",
  "Particle board dust": "/materials/wood-dust",
  "Furniture dust": "/materials/wood-dust",
  "Wood sanding dust": "/materials/wood-dust",
  "Wood routing dust": "/materials/wood-dust",
  "Wood pellet dust": "/materials/wood-dust",
  "Rice dust": "/materials/grain-dust",
  "Barley dust": "/materials/grain-dust",
  "Oat dust": "/materials/grain-dust",
  "Rye dust": "/materials/grain-dust",
  "Baking mix dust": "/materials/flour-dust",
  "Baking powder": "/materials/flour-dust",
  "Breadcrumb dust": "/materials/flour-dust",
  "Nylon powder": "/materials/plastic-dust",
  "Nylon PA12 powder": "/materials/plastic-dust",
  "Nylon fiber dust": "/materials/plastic-dust",
  "Polymer printing powder": "/materials/plastic-dust",
  "Melamine powder": "/materials/plastic-dust",
  "Resin sanding dust": "/materials/plastic-dust",
  "Fiberglass resin dust": "/materials/plastic-dust",
  "Rubber dust": "/materials/rubber-dust",
  "Rubber powder": "/materials/rubber-dust",
  "Rubber crumb": "/materials/rubber-dust",
  "Paper dust": "/materials/paper-dust",
  "Pulp dust": "/materials/paper-dust",
  "Cellulose dust": "/materials/paper-dust",
  "Cardboard dust": "/materials/paper-dust",
  "Tissue dust": "/materials/paper-dust",
  "Leather dust": "/materials/leather-dust",
  "Cork dust": "/materials/cork-dust",
  "Tobacco dust": "/materials/tobacco-dust",
  "Carbon steel dust": "/materials/iron-dust",
  "Stainless steel dust": "/materials/iron-dust",
  "Stainless steel powder": "/materials/iron-dust",
  "Tool steel dust": "/materials/iron-dust",
  "Brass dust": "/materials/brass-bronze-dust",
  "Bronze dust": "/materials/brass-bronze-dust",
  "Solder dust": "/materials/tin-dust",
  "Bamboo dust": "/materials/wood-dust",
  "Clay dust": "/materials/silica-dust",
  "Gypsum dust": "/materials/concrete-cement-dust",
  "Soybean dust": "/materials/grain-dust",
  "Seed dust": "/materials/grain-dust",
  "Anode powder": "/materials/graphite-dust",
  "Cathode powder": "/materials/lithium-dust",
  "Rayon dust": "/materials/cotton-wool-dust",
  "Fabric lint": "/materials/cotton-wool-dust",
  "Tire dust": "/materials/rubber-dust",
  "Polyester fiber dust": "/materials/plastic-dust",
  "Inconel powder": "/materials/nickel-dust",
  "Dolomite dust": "/materials/concrete-cement-dust",
  "Charcoal dust": "/materials/carbon-black",
  "Biochar dust": "/materials/carbon-black",
};

export function MaterialsDirectory() {
  return (
    <DirectoryExplorer
      groups={MATERIAL_GROUPS}
      featuredLinks={FEATURED_ITEM_LINKS}
      searchLabel="Search the dusts and materials directory"
      searchPlaceholder="Search dusts and materials — sugar, magnesium, PA12…"
    />
  );
}
