"use client";

import { DirectoryExplorer } from "@/components/directory/directory-explorer";
import { MATERIAL_GROUPS } from "@/lib/data/materials";

const FEATURED_ITEM_LINKS: Record<string, string> = {
  "ABS dust": "/materials/plastic-dust",
  "API dust": "/industries/pharmaceutical",
  "Acrylic dust": "/materials/plastic-dust",
  "Activated carbon": "/materials/activated-carbon",
  "Agricultural biomass dust": "/materials/agricultural-biomass-dust",
  "Aluminum dust": "/materials/aluminum-dust",
  "Aluminum fines": "/materials/aluminum-dust",
  "Aluminum grinding dust": "/materials/aluminum-dust",
  "Aluminum powder": "/materials/aluminum-dust",
  "Anode powder": "/materials/conductive-carbon",
  "Arsenic dust": "/materials/arsenic-dust",
  "Asbestos-containing debris": "/materials/asbestos",
  "Bakery dust": "/materials/flour-dust",
  "Baking mix dust": "/materials/flour-dust",
  "Baking powder": "/materials/flour-dust",
  "Bamboo dust": "/materials/wood-dust",
  "Barley dust": "/materials/grain-dust",
  "Battery black mass": "/materials/battery-black-mass",
  "Beryllium dust": "/materials/beryllium-dust",
  "Biochar dust": "/materials/biomass-dust",
  "Biomass dust": "/materials/biomass-dust",
  "Blending dust": "/applications/mixing-blending",
  "Brass dust": "/materials/brass-bronze-dust",
  "Breadcrumb dust": "/materials/flour-dust",
  "Bronze dust": "/materials/brass-bronze-dust",
  "Cadmium dust": "/materials/cadmium-dust",
  "Calcium metal dust": "/materials/calcium-dust",
  "Capsule dust": "/materials/gelatin-powder",
  "Carbon black": "/materials/carbon-black",
  "Carbon fiber dust": "/materials/carbon-fiber-dust",
  "Carbon steel dust": "/materials/iron-dust",
  "Cardboard dust": "/materials/corrugated-paper-dust",
  "Cathode powder": "/materials/lithium-dust",
  "Cellulose dust": "/materials/paper-dust",
  "Cement kiln dust": "/materials/concrete-cement-dust",
  "Ceramic substrate dust": "/industries/glass-ceramics",
  "Charcoal dust": "/materials/carbon-black",
  "Chocolate powder": "/materials/cocoa-dust",
  "Chromium dust": "/materials/chromium-dust",
  "Cinnamon dust": "/materials/cinnamon-dust",
  "Clay dust": "/materials/silica-dust",
  "Coal dust": "/materials/coal-dust",
  "Cobalt dust": "/materials/cobalt-dust",
  "Cobalt powder": "/materials/cobalt-dust",
  "Cocoa powder": "/materials/cocoa-dust",
  "Coffee dust": "/materials/coffee-dust",
  "Coke dust": "/materials/coke-dust",
  "Combustible metal dust": "/materials/combustible-metal-dust",
  "Composite material dust": "/materials/carbon-fiber-dust",
  "Conductive carbon": "/materials/conductive-carbon",
  "Copper dust": "/materials/copper-dust",
  "Copper fines": "/materials/copper-dust",
  "Cork dust": "/materials/cork-dust",
  "Corn dust": "/materials/corn-dust",
  "Corn starch": "/materials/corn-dust",
  "Cosmetic powder": "/materials/cosmetic-powder",
  "Cotton dust": "/materials/cotton-wool-dust",
  "Cotton lint": "/materials/cotton-wool-dust",
  "Detergent powder": "/materials/detergent-powder",
  "Dolomite dust": "/materials/concrete-cement-dust",
  "Dye powder": "/materials/dye-powder",
  "Egg powder": "/materials/egg-powder",
  "Excipient dust": "/industries/pharmaceutical",
  "Fabric lint": "/materials/textile-fibers",
  "Feed dust": "/materials/grain-dust",
  "Fertilizer dust": "/materials/fertilizer-dust",
  "Fiberglass resin dust": "/materials/plastic-dust",
  "Flour": "/materials/flour-dust",
  "Flour dust": "/materials/flour-dust",
  "Furniture dust": "/materials/wood-dust",
  "Garlic powder": "/materials/garlic-powder",
  "Gelatin powder": "/materials/gelatin-powder",
  "Gold dust": "/materials/combustible-metal-dust",
  "Grain dust": "/materials/grain-dust",
  "Graphite dust": "/materials/graphite-dust",
  "Gypsum dust": "/materials/concrete-cement-dust",
  "Hardwood dust": "/materials/wood-dust",
  "Hay dust": "/materials/agricultural-biomass-dust",
  "Hemp dust": "/industries/cannabis",
  "Inconel powder": "/materials/nickel-dust",
  "Iron dust": "/materials/iron-dust",
  "Iron oxide dust": "/materials/iron-dust",
  "Lactose powder": "/industries/pharmaceutical",
  "Lead dust": "/materials/lead-dust",
  "Leather dust": "/materials/leather-dust",
  "Limestone dust": "/materials/concrete-cement-dust",
  "Lithium dust": "/materials/lithium-dust",
  "Lithium metal dust": "/materials/lithium-dust",
  "MDF dust": "/materials/wood-dust",
  "Magnesium dust": "/materials/magnesium-dust",
  "Magnesium powder": "/materials/magnesium-dust",
  "Malt dust": "/materials/malt-dust",
  "Mercury": "/materials/mercury",
  "Manganese dust": "/materials/manganese-dust",
  "Manganese powder": "/materials/manganese-dust",
  "Melamine powder": "/materials/plastic-dust",
  "Microcrystalline cellulose": "/materials/paper-dust",
  "Milk powder": "/materials/milk-powder",
  "Nickel alloy powder": "/materials/nickel-dust",
  "Nickel dust": "/materials/nickel-dust",
  "Nickel powder": "/materials/nickel-dust",
  "Nutraceutical powder": "/materials/protein-powder",
  "Nylon PA12 powder": "/materials/plastic-dust",
  "Nylon fiber dust": "/materials/textile-fibers",
  "Nylon powder": "/materials/plastic-dust",
  "OSB dust": "/materials/wood-dust",
  "Oat dust": "/materials/grain-dust",
  "Onion powder": "/materials/onion-powder",
  "PCB dust": "/industries/electronics",
  "PET dust": "/materials/plastic-dust",
  "PVC dust": "/materials/plastic-dust",
  "PVC powder": "/materials/plastic-dust",
  "Paper dust": "/materials/paper-dust",
  "Paprika dust": "/materials/paprika-dust",
  "Particle board dust": "/materials/wood-dust",
  "Pea protein": "/materials/pea-protein",
  "Pellet dust": "/materials/pellet-dust",
  "Pepper dust": "/materials/pepper-dust",
  "Phosphate dust": "/materials/phosphate-dust",
  "Pigment dust": "/materials/pigment-dust",
  "Plastic powder": "/materials/plastic-dust",
  "Plywood dust": "/materials/wood-dust",
  "Polycarbonate dust": "/materials/plastic-dust",
  "Polyester fiber dust": "/materials/textile-fibers",
  "Polyethylene powder": "/materials/plastic-dust",
  "Polymer dust": "/materials/plastic-dust",
  "Polymer printing powder": "/materials/plastic-dust",
  "Polypropylene powder": "/materials/plastic-dust",
  "Polyurethane dust": "/materials/plastic-dust",
  "Potash dust": "/materials/potash-dust",
  "Potato starch": "/materials/starch-dust",
  "Powdered sugar": "/materials/sugar-dust",
  "Precious metal polishing dust": "/materials/combustible-metal-dust",
  "Protein powder": "/materials/protein-powder",
  "Pulp dust": "/materials/paper-dust",
  "Rayon dust": "/materials/textile-fibers",
  "Resin dust": "/materials/plastic-dust",
  "Resin sanding dust": "/materials/plastic-dust",
  "Rice dust": "/materials/grain-dust",
  "Rice starch": "/materials/starch-dust",
  "Rubber crumb": "/materials/rubber-dust",
  "Rubber dust": "/materials/rubber-dust",
  "Rubber powder": "/materials/rubber-dust",
  "Rye dust": "/materials/grain-dust",
  "Sawdust": "/materials/sawdust",
  "Seed dust": "/materials/grain-dust",
  "Semiconductor dust": "/industries/electronics",
  "Silica-containing dust": "/materials/silica-dust",
  "Silicon carbide dust": "/materials/silica-dust",
  "Silicon dust": "/industries/electronics",
  "Silver dust": "/materials/combustible-metal-dust",
  "Soap powder": "/materials/soap-powder",
  "Softwood dust": "/materials/wood-dust",
  "Solder dust": "/materials/tin-dust",
  "Soy protein": "/materials/soy-protein",
  "Soybean dust": "/materials/grain-dust",
  "Spice dust": "/materials/spice-dust",
  "Stainless steel dust": "/materials/iron-dust",
  "Stainless steel powder": "/materials/iron-dust",
  "Straw dust": "/materials/agricultural-biomass-dust",
  "Sugar dust": "/materials/sugar-dust",
  "Sulfur dust": "/materials/sulfur-dust",
  "Tablet dust": "/industries/pharmaceutical",
  "Talc": "/materials/cosmetic-powder",
  "Tea dust": "/materials/tea-dust",
  "Tin dust": "/materials/tin-dust",
  "Tire dust": "/materials/rubber-dust",
  "Tissue dust": "/materials/paper-dust",
  "Titanium dust": "/materials/titanium-dust",
  "Titanium powder": "/materials/titanium-dust",
  "Tobacco dust": "/materials/tobacco-dust",
  "Tool steel dust": "/materials/iron-dust",
  "Urea dust": "/materials/urea-dust",
  "Veneer dust": "/materials/wood-dust",
  "Vitamin powder": "/industries/pharmaceutical",
  "Wax powder": "/materials/wax-powder",
  "Wheat dust": "/materials/grain-dust",
  "Wheat starch": "/materials/starch-dust",
  "Whey powder": "/materials/whey-powder",
  "Wood pellet dust": "/materials/pellet-dust",
  "Wood routing dust": "/materials/wood-dust",
  "Wood sanding dust": "/materials/wood-dust",
  "Wool dust": "/materials/cotton-wool-dust",
  "Zinc dust": "/materials/zinc-dust",
  "Zirconium dust": "/materials/zirconium-dust",
};

export function MaterialsDirectory() {
  return (
    <DirectoryExplorer
      groups={MATERIAL_GROUPS}
      featuredLinks={FEATURED_ITEM_LINKS}
      searchLabel="Search the dusts and materials directory"
      searchPlaceholder="Search dusts and materials — sugar, magnesium, PA12…"
    />
  );
}
