#!/usr/bin/env python3
"""Extract PrestiVac factory brochures (docx) into structured line data.

Brand rule: DUTYVAC -> PrestiVac (client-confirmed). Placeholder specs
("xx dB" etc.) are dropped, never shipped. Photographed-series mapping is
LINE-LEVEL only (brochure nomenclature differs from current model names);
per-model identity is never asserted.
"""
import glob, json, os, re, sys
from collections import Counter
from docx import Document

BASE = sys.argv[1] if len(sys.argv) > 1 else "/home/claude/brochures-extract/BROCHURES Englsih"
OUT_TS = "src/lib/data/factory-lines.ts"
OUT_REPORT = "docs/factory-brochures/extract-report.txt"

FAMILIES = {
    "avx": ("Explosion Proof/Dry Collection/Pneumatic",
            "Air-operated explosion-proof line (brochure family: pneumatic dry collection)"),
    "evx": ("Explosion Proof/Dry Collection/Electric Division 1",
            "Electric Division 1 explosion-proof line (brochure family: electric dry collection)"),
    "ex1": ("Hepa/Dry Collection/Electric",
            "HEPA industrial electric line (brochure family: HEPA dry collection)"),
    "av1": ("Industrial/Dry Collection/Air",
            "Compact industrial air-operated line"),
    "ev1": ("Industrial/Dry Collection/Electric",
            "Compact industrial electric line"),
}

def clean(t):
    t = t.replace("DUTYVAC SYSTEMS INC.", "PrestiVac Systems Inc.")
    t = re.sub(r"DUTYVAC", "PrestiVac", t)
    return re.sub(r"\s+", " ", t).strip()

CERT_PAT = re.compile(r"(Class I,|EPL |II \d ?GD|Certified)", re.I)
PLACEHOLDER = re.compile(r"\bxx\b", re.I)
NUM = lambda pat, s: (re.search(pat, s, re.I) or [None]) and (re.search(pat, s, re.I).group(1) if re.search(pat, s, re.I) else None)

def parse(path):
    doc = Document(path)
    paras = [clean(p.text) for p in doc.paragraphs if p.text.strip()]
    model = os.path.basename(path)[:-5]
    mtok = []
    for w in model.split():
        if re.fullmatch(r"[A-Z0-9.\-/&]+", w): mtok.append(w)
        else: break
    model = " ".join(mtok) or model
    cert, features, filtration, intro = [], [], [], []
    section = "head"
    for p in paras:
        low = p.lower()
        if low.startswith("features"): section = "features"; continue
        if low.startswith("filtration"): section = "filtration"; continue
        if low.startswith(("applications", "industries", "if you ")): section = "tail"; continue
        if section == "head":
            if CERT_PAT.search(p) and len(p) < 220: cert.append(p)
            elif len(p) > 120: intro.append(p)
        elif section == "features" and not PLACEHOLDER.search(p): features.append(p)
        elif section == "filtration" and not PLACEHOLDER.search(p): filtration.append(p)
    perf = " ".join(features)
    return {
        "model": model, "file": os.path.relpath(path, BASE),
        "cert": cert, "intro": intro[:1], "features": features, "filtration": filtration,
        "h2o": NUM(r"([\d.]+)\s*[”\"]\s*H2O", perf), "cfm": NUM(r"([\d.]+)\s*CFM", perf),
        "airwatts": NUM(r"([\d,]+)\s*Peak Air Watts", perf),
    }

all_files = glob.glob(f"{BASE}/**/*.docx", recursive=True)
parsed_all = []
for f in all_files:
    try: parsed_all.append(parse(f))
    except Exception as e: print(f"SKIP {f}: {e}", file=sys.stderr)

lines = {}
for sid, (folder, label) in FAMILIES.items():
    fam = [p for p in parsed_all if p["file"].startswith(folder + os.sep) or p["file"].startswith(folder + "/")]
    if not fam: continue
    def mode(key):
        c = Counter(tuple(p[key]) for p in fam if p[key])
        return list(c.most_common(1)[0][0]) if c else []
    sizes = sorted(
        ({"model": p["model"], "h2o": p["h2o"], "cfm": p["cfm"], "airwatts": p["airwatts"]}
         for p in fam),
        key=lambda r: (len(r["model"]), r["model"]))
    seen, dedup = set(), []
    for r in sizes:
        if r["model"] in seen: continue
        seen.add(r["model"]); dedup.append(r)
    lines[sid] = {"label": label, "docCount": len(fam), "cert": mode("cert"),
                  "features": mode("features")[:8], "filtration": mode("filtration")[:5],
                  "sizes": dedup[:10]}

os.makedirs(os.path.dirname(OUT_REPORT), exist_ok=True)
with open(OUT_REPORT, "w") as r:
    r.write(f"Extracted {len(parsed_all)}/{len(all_files)} brochures\n")
    for sid, L in lines.items():
        r.write(f"\n[{sid}] {L['docCount']} docs; sizes: {[s['model'] for s in L['sizes']]}\n")
        for c in L["cert"]: r.write(f"  CERT: {c}\n")

banner = ("/**\n * GENERATED by scripts/extract-brochures.py — do not hand-edit.\n"
          f" * Source: factory brochure corpus ({len(parsed_all)} documents parsed).\n"
          " * Brand substituted per client instruction; placeholder specs dropped.\n"
          " * Mapping is LINE-LEVEL: brochure families correspond to photographed\n"
          " * series by category, not by per-model identity.\n */\n")
ts = banner + "export type FactoryLine = {\n  label: string;\n  docCount: number;\n  cert: string[];\n  features: string[];\n  filtration: string[];\n  sizes: { model: string; h2o: string | null; cfm: string | null; airwatts: string | null }[];\n};\n\n"
ts += "export const FACTORY_LINES: Record<string, FactoryLine> = " + json.dumps(lines, indent=2, ensure_ascii=False) + ";\n"
ts += f"\nexport const BROCHURE_CORPUS_SIZE = {len(parsed_all)};\n"
open(OUT_TS, "w").write(ts)
print(f"wrote {OUT_TS} ({len(lines)} lines) + report")
for sid, L in lines.items():
    print(f"  {sid}: {L['docCount']} docs, {len(L['sizes'])} sizes, {len(L['cert'])} cert lines")
