/**
 * GENERATED by scripts/extract-brochures.py — do not hand-edit.
 * Source: factory brochure corpus (410 documents parsed).
 * Brand substituted per client instruction; placeholder specs dropped.
 * Mapping is LINE-LEVEL: brochure families correspond to photographed
 * series by category, not by per-model identity.
 */
export type FactoryLine = {
 label: string;
 docCount: number;
 cert: string[];
 features: string[];
 filtration: string[];
 sizes: { model: string; h2o: string | null; cfm: string | null; airwatts: string | null }[];
};

export const FACTORY_LINES: Record<string, FactoryLine> = {
 "avx": {
 "label": "Air-operated explosion-proof line (brochure family: pneumatic dry collection)",
 "docCount": 24,
 "cert": [
 "II 2 GD c IIC T6 (85oC)",
 "Class I, Division 1, Groups A, B, C and D T6 and Class II, Division 1, Groups E, F, G Hazardous Locations as defined in the National Electric Code (NEC) and NFPA 70",
 "Certified EPL Db and EPL Gb (Equipment Protection Level)"
 ],
 "features": [
 "Double Venturi generates Powerful Heavy Duty suction with over 180” H2O Vacuum and 200 CFM",
 "Air operated Pneumatic units do not have any electrical components or moving parts so they can run continuously and will not overheat or breakdown",
 "Static dissipating ESD safe",
 "All Stainless steel construction makes it a solid unit that is easy to clean and sterilize",
 "Stainless steel industrial cart assembly with ESD safe, conductive wheels",
 "Complete with static dissipating suction hose and accessories",
 "Quiet operation with only 60 dB"
 ],
 "filtration": [
 "Activated Carbon Filtration System to adsorb fumes and vapors",
 "Conductive ESD safe filters",
 "HEPA Filtration with an efficiency of 99.995% @ 0.3 micron. Tested: IEST RP-CC001.3. H14 by MPPS method as per EN 1822 and OSHA compliant"
 ],
 "sizes": [
 {
 "model": "AV1-5 EX",
 "h2o": "180",
 "cfm": "100",
 "airwatts": null
 },
 {
 "model": "AV2-5 EX",
 "h2o": "180",
 "cfm": "200",
 "airwatts": null
 },
 {
 "model": "AV1-10 EX",
 "h2o": "180",
 "cfm": "100",
 "airwatts": null
 },
 {
 "model": "AV1-25 EX",
 "h2o": "180",
 "cfm": "100",
 "airwatts": null
 },
 {
 "model": "AV1-55 EX",
 "h2o": "180",
 "cfm": "100",
 "airwatts": null
 },
 {
 "model": "AV2-10 EX",
 "h2o": "180",
 "cfm": "200",
 "airwatts": null
 },
 {
 "model": "AV2-25 EX",
 "h2o": "180",
 "cfm": "200",
 "airwatts": null
 },
 {
 "model": "AV2-55 EX",
 "h2o": "180",
 "cfm": "200",
 "airwatts": null
 },
 {
 "model": "AV1-5 EX ACF",
 "h2o": "180",
 "cfm": "100",
 "airwatts": null
 },
 {
 "model": "AV1-5 EX RCT",
 "h2o": "180",
 "cfm": "100",
 "airwatts": null
 }
 ]
 },
 "evx": {
 "label": "Electric Division 1 explosion-proof line (brochure family: electric dry collection)",
 "docCount": 12,
 "cert": [
 "Certified EPL Db and EPL Gb (Equipment Protection Level)"
 ],
 "features": [
 "Single phase Explosion Proof motor with 321 Peak Air Watts, 68” H2O Vacuum and 142 CFM",
 "Static dissipating ESD safe",
 "All Stainless steel construction makes it a solid unit that is easy to clean and sterilize",
 "Stainless steel industrial cart assembly with ESD safe, conductive wheels",
 "Complete with static dissipating suction hose and accessories"
 ],
 "filtration": [
 "Activated Carbon Filtration System to adsorb fumes and vapors",
 "Conductive ESD safe filters",
 "HEPA Filtration with an efficiency of 99.995% @ 0.3 micron. Tested: IEST RP-CC001.3. H14 by MPPS method as per EN 1822 and OSHA compliant"
 ],
 "sizes": [
 {
 "model": "EX-5",
 "h2o": "68",
 "cfm": "142",
 "airwatts": "321"
 },
 {
 "model": "EX-10",
 "h2o": "68",
 "cfm": "142",
 "airwatts": "321"
 },
 {
 "model": "EX-25",
 "h2o": "68",
 "cfm": "142",
 "airwatts": "321"
 },
 {
 "model": "EX-55",
 "h2o": "68",
 "cfm": "142",
 "airwatts": "321"
 },
 {
 "model": "EX-5 ACF",
 "h2o": "68",
 "cfm": "142",
 "airwatts": "321"
 },
 {
 "model": "EX-5 RCT",
 "h2o": "68",
 "cfm": "142",
 "airwatts": "321"
 },
 {
 "model": "EX-10 ACF",
 "h2o": "68",
 "cfm": "142",
 "airwatts": "321"
 },
 {
 "model": "EX-10 RCT",
 "h2o": "68",
 "cfm": "142",
 "airwatts": "321"
 },
 {
 "model": "EX-25 ACF",
 "h2o": "68",
 "cfm": "142",
 "airwatts": "321"
 },
 {
 "model": "EX-55 ACF",
 "h2o": "68",
 "cfm": "142",
 "airwatts": "321"
 }
 ]
 },
 "ex1": {
 "label": "HEPA industrial electric line (brochure family: HEPA dry collection)",
 "docCount": 14,
 "cert": [],
 "features": [
 "Double Motor produces powerful suction with over 1000+ Peak Air Watts, 135” H2O Vacuum and 230 CFM",
 "Stainless steel construction makes it a solid unit that is easy to clean and sterilize",
 "Industrial Stainless steel cart assembly",
 "Static dissipating ESD safe",
 "Complete with suction hose and accessories"
 ],
 "filtration": [
 "3-stage filtration system for maximum performance and efficiency",
 "Washable, reusable filters",
 "Absolute HEPA Filtration with an efficiency of 99.995% @ 0.3 micron",
 "HEPA Filtration with an efficiency of 99.995% @ 0.3 micron. Tested: IEST RP-CC001.3. H14 by MPPS method as per EN 1822 and OSHA compliant",
 "Activated Carbon Filtration System to adsorb fuel and solvent fumes and vapors"
 ],
 "sizes": [
 {
 "model": "EV1-5 HEPA",
 "h2o": "135",
 "cfm": "123",
 "airwatts": "560"
 },
 {
 "model": "EV2-5 HEPA",
 "h2o": "135",
 "cfm": "230",
 "airwatts": null
 },
 {
 "model": "EV1-10 HEPA",
 "h2o": "135",
 "cfm": "123",
 "airwatts": "560"
 },
 {
 "model": "EV1-25 HEPA",
 "h2o": "135",
 "cfm": "123",
 "airwatts": "560"
 },
 {
 "model": "EV1-55 HEPA",
 "h2o": "135",
 "cfm": "123",
 "airwatts": "560"
 },
 {
 "model": "EV2-10 HEPA",
 "h2o": "135",
 "cfm": "230",
 "airwatts": null
 },
 {
 "model": "EV2-25 HEPA",
 "h2o": "135",
 "cfm": "230",
 "airwatts": null
 },
 {
 "model": "EV2-55 HEPA",
 "h2o": "135",
 "cfm": "230",
 "airwatts": null
 },
 {
 "model": "EV1-5 HEPA RCT",
 "h2o": "135",
 "cfm": "123",
 "airwatts": "560"
 },
 {
 "model": "EV1-55 HEPA DT",
 "h2o": "135",
 "cfm": "123",
 "airwatts": "560"
 }
 ]
 },
 "av1": {
 "label": "Compact industrial air-operated line",
 "docCount": 14,
 "cert": [],
 "features": [
 "Double Venturi generates Powerful Heavy Duty suction with over 180” H2O Vacuum and 200 CFM",
 "Stainless steel construction makes it a solid unit that is easy to clean and sterilize",
 "Industrial Stainless steel cart assembly",
 "Complete with suction hose, compressed air supply hose and accessories",
 "Quiet operation with only 60 dB"
 ],
 "filtration": [
 "3-stage filtration system for maximum performance and efficiency",
 "Washable, reusable filters",
 "Collection filter bag",
 "HEPA Filtration with an efficiency of 99.995% @ 0.3 micron. Tested: IEST RP-CC001.3. H14 by MPPS method as per EN 1822 and OSHA compliant",
 "Activated Carbon Filtration System to adsorb fumes and vapors"
 ],
 "sizes": [
 {
 "model": "AV1-5",
 "h2o": "180",
 "cfm": "100",
 "airwatts": null
 },
 {
 "model": "AV2-5",
 "h2o": "180",
 "cfm": "200",
 "airwatts": null
 },
 {
 "model": "AV1-10",
 "h2o": "180",
 "cfm": "100",
 "airwatts": null
 },
 {
 "model": "AV1-25",
 "h2o": "180",
 "cfm": "100",
 "airwatts": null
 },
 {
 "model": "AV1-55",
 "h2o": "180",
 "cfm": "100",
 "airwatts": null
 },
 {
 "model": "AV2-10",
 "h2o": "180",
 "cfm": "200",
 "airwatts": null
 },
 {
 "model": "AV2-25",
 "h2o": "180",
 "cfm": "200",
 "airwatts": null
 },
 {
 "model": "AV2-55",
 "h2o": "180",
 "cfm": "200",
 "airwatts": null
 },
 {
 "model": "AV1-5 RCT",
 "h2o": "180",
 "cfm": "100",
 "airwatts": null
 },
 {
 "model": "AV1-55 DT",
 "h2o": "180",
 "cfm": "100",
 "airwatts": null
 }
 ]
 },
 "ev1": {
 "label": "Compact industrial electric line",
 "docCount": 13,
 "cert": [],
 "features": [
 "Powerful motor with 560 Peak Air Watts, 135” of Vacuum and 123 CFM",
 "Stainless steel construction makes it a solid unit that is easy to clean and sterilize",
 "Industrial Stainless steel cart assembly",
 "Static dissipating ESD safe",
 "Complete with suction hose and accessories"
 ],
 "filtration": [
 "2-stage filtration system for maximum performance and efficiency",
 "Washable, reusable filters",
 "HEPA Filtration with an efficiency of 99.995% @ 0.3 micron. Tested: IEST RP-CC001.3. H14 by MPPS method as per EN 1822 and OSHA compliant",
 "Activated Carbon Filtration System to adsorb fuel and solvent fumes and vapors"
 ],
 "sizes": [
 {
 "model": "EV1-5",
 "h2o": null,
 "cfm": "123",
 "airwatts": "560"
 },
 {
 "model": "EV1-10",
 "h2o": null,
 "cfm": "123",
 "airwatts": "560"
 },
 {
 "model": "EV1-25",
 "h2o": null,
 "cfm": "123",
 "airwatts": "560"
 },
 {
 "model": "EV1-55",
 "h2o": null,
 "cfm": "123",
 "airwatts": "560"
 },
 {
 "model": "EV2-10",
 "h2o": "135",
 "cfm": "230",
 "airwatts": null
 },
 {
 "model": "EV2-25",
 "h2o": "135",
 "cfm": "230",
 "airwatts": null
 },
 {
 "model": "EV2-55",
 "h2o": "135",
 "cfm": "230",
 "airwatts": null
 },
 {
 "model": "EV1-5 RCT",
 "h2o": null,
 "cfm": "123",
 "airwatts": "560"
 },
 {
 "model": "EV1-55 DT",
 "h2o": "135",
 "cfm": "123",
 "airwatts": "560"
 },
 {
 "model": "EV2-5 RCT",
 "h2o": "135",
 "cfm": "230",
 "airwatts": null
 }
 ]
 }
};

export const BROCHURE_CORPUS_SIZE = 410;
