import type { GuideArticle } from "@/components/templates/guide-article";

/**
 * Selection guides — "how to choose / how to size" decision content.
 *
 * Integrity rules (same as GUIDE_ARTICLES in guides.ts):
 * - PrestiVac manufactures industrial vacuums, NOT dust collectors.
 * - No Kst, MIE, MEC or exposure values are stated, and no airflow, vacuum or
 * capacity figures are quoted. Sizing is described as a method, and specific
 * numbers are referred to the datasheet for the model.
 * - Certification scope is never asserted generically. Suitability is
 * described as a property of a specific model against a specific area
 * classification, verified from its documentation.
 * - Nothing here states a specific NFPA/OSHA/ATEX clause or requirement, and
 * nothing here substitutes for a Dust Hazard Analysis or a qualified
 * engineering review.
 */
export const SELECTION_GUIDES: GuideArticle[] = [
  {
    slug: "how-to-choose-an-explosion-proof-vacuum",
    name: "Choosing an explosion-proof vacuum",
    title: "How to choose an explosion-proof vacuum, in the right order",
    eyebrow: "Buying guide",
    minutes: 8,
    seo: {
      title: "How to Choose an Explosion Proof Vacuum",
      description:
        "The specification sequence that avoids expensive mistakes: identify the material, establish the area classification, then select construction, power source and filtration — in that order.",
    },
    heroIntro:
      "Most specification problems come from doing this in the wrong order — starting with a product category, or with a budget, and working backwards to justify it. The sequence below works because each step constrains the next. Get the first two right and the rest becomes a short conversation; get them wrong and nothing downstream can rescue it.",
    keyPoints: [
      "Material first — it determines everything that follows",
      "Area classification second — it determines what equipment is eligible",
      "Power source, filtration and capacity are downstream of both",
      "Suitability is a property of a specific model, verified from its documentation",
    ],
    sections: [
      {
        heading: "Step 1 — Identify the material properly",
        body: [
          "Everything downstream depends on knowing what you are actually recovering. Not the general category — the specific material, including its fine fraction, because combustibility rises sharply as particle size falls and the fines are usually what matters. A material that is inert as chips or granules can be a genuine hazard as dust.",
          "Where the material has not been characterised, testing is the honest first step rather than an assumption. This is also where reactivity questions get settled: whether the material can be safely wetted, whether it is conductive, whether it self-heats. Those properties change the recovery method, not just the equipment.",
        ],
      },
      {
        heading: "Step 2 — Establish the area classification",
        body: [
          "The classification of the space where the vacuum will be used determines what equipment is eligible. This is assigned by your electrical or process engineer, and it is not something a vacuum supplier can determine on your behalf — it is a property of the facility and its process, documented as part of the plant's hazardous area assessment.",
          "If the classification has not been assigned, that is the blocker to resolve first. A specification built on an assumed classification is a specification that may have to be redone. Where a unit will move between areas, it is the most severe classification it will enter that governs.",
        ],
      },
      {
        heading: "Step 3 — Match construction to the hazard",
        body: [
          "With material and classification established, construction follows. This covers whether the requirement is for Class I protection, Class II protection or both; the relevant groups; and the temperature code appropriate to the location. It also covers the flow path — whether the hose, tools and container need to be conductive and part of a grounded, bonded system.",
          "Static control deserves specific attention because it is generated by the process of vacuuming itself. Material moving at speed through a hose generates charge regardless of what drives the airflow, which is why the grounding and bonding path is specified as a complete circuit from tool to container rather than as a feature of the machine.",
        ],
      },
      {
        heading: "Step 4 — Choose the power source",
        body: [
          "Pneumatic units have no electrical components on the recovery unit at all; electric units use a motor built and certified for the classification. The practical decision usually turns on what the facility can supply and how long the unit will run: compressed air availability at the point of use, and duty cycle.",
          "Short intermittent housekeeping suits pneumatic units well. Sustained duty tends to favour electric, because compressed air is an expensive utility per unit of work and the gap widens the longer the unit runs. Neither choice is a certification in itself.",
        ],
      },
      {
        heading: "Step 5 — Specify filtration and capacity",
        body: [
          "Filtration is specified as a system — medium, filter area, housing seal and change-out method — rather than as a grade on a label. Generous filter area sustains airflow and lengthens service life, which matters because every filter change in a hazardous or toxic application is itself a handling and exposure event.",
          "Capacity is set by how much material accumulates between emptying events and by how that container will be handled. A container sized for volume alone can be unmanageable in practice, particularly with dense material or liquid. How the container is removed and emptied is part of the specification, not an afterthought.",
        ],
      },
      {
        heading: "Step 6 — Verify against documentation",
        body: [
          "The final step is confirming that the specific model and configuration you intend to buy carries documentation covering your classification. Certification covers a named model and configuration with a defined scope — the classes, groups and temperature code stated on the certificate.",
          "Check that scope against your area classification, and confirm that any configuration options you have added fall within it. An option added to a base unit can sit outside the scope of the listing that covers the base model.",
        ],
      },
    ],
    callout: {
      heading: "This does not replace a Dust Hazard Analysis",
      body: [
        "A vacuum specification is one output of a wider hazard assessment, not a substitute for it. Where a Dust Hazard Analysis has been carried out, its conclusions govern.",
        "Where safety-critical decisions are involved, equipment selection belongs with a qualified engineer who knows the process and the facility.",
      ],
    },
    faqs: [
      {
        question: "Can you tell me which vacuum I need from the material alone?",
        answer:
          "Material narrows it considerably but does not settle it. The area classification, the duty cycle, the available utilities and the capacity requirement all shape the answer. Material and classification together get most of the way there.",
      },
      {
        question: "Who assigns the area classification?",
        answer:
          "Your electrical or process engineer, as part of the facility's hazardous area assessment. It is a property of your process and space, and it is not something an equipment supplier can determine for you.",
      },
      {
        question: "What if the classification has not been assigned yet?",
        answer:
          "That is the first thing to resolve, because it determines which equipment is eligible. A specification built on an assumed classification may have to be redone once the real one is established.",
      },
      {
        question: "Does a certified unit stay certified?",
        answer:
          "Only while it remains in its listed configuration and condition. Equipment that has been opened, modified or repaired outside that configuration is no longer the equipment that was certified, which is why maintenance is part of the protection rather than separate from it.",
      },
    ],
    related: [
      { label: "Explosion Proof Vacuums", href: "/products/explosion-proof-vacuums" },
      { label: "Electric vs pneumatic", href: "/guides/electric-vs-pneumatic-vacuums" },
      { label: "Dust hazard analysis", href: "/guides/dust-hazard-analysis" },
      { label: "Hazardous location vacuums", href: "/hazardous-location-vacuums" },
      { label: "Get a quote", href: "/get-a-quote" },
    ],
  },

  {
    slug: "how-to-choose-a-combustible-dust-vacuum",
    name: "Choosing a combustible dust vacuum",
    title: "Choosing a vacuum for combustible dust",
    eyebrow: "Buying guide",
    minutes: 7,
    seo: {
      title: "How to Choose a Combustible Dust Vacuum",
      description:
        "What changes when the dust is combustible: removing ignition sources from the collection path, controlling static, preventing a dispersed cloud inside the machine, and handling what has been collected.",
    },
    heroIntro:
      "Combustible dust changes the specification because the machine itself becomes part of the hazard analysis. A vacuum takes settled material and deliberately disperses it into a moving airstream inside a confined enclosure — which is precisely the arrangement that dust safety exists to prevent. Everything about a properly specified unit is aimed at making that safe.",
    keyPoints: [
      "The machine creates a dispersed cloud by design — that is the core problem",
      "Ignition sources must be removed from the entire collection path",
      "Static is generated by vacuuming itself, regardless of power source",
      "Collected material remains a hazard until it is properly handled",
    ],
    sections: [
      {
        heading: "Why the machine is part of the hazard",
        body: [
          "A dust deflagration needs fuel, dispersion, confinement, oxygen and an ignition source together. Settled dust on a floor supplies fuel and nothing else. A vacuum supplies dispersion and confinement as a matter of normal operation, and it does so with the fuel already present.",
          "That is not an argument against vacuuming — removal and containment is the correct control, and the alternatives are worse. Sweeping raises clouds. Compressed air disperses material far more aggressively and puts it where it was not before. It is an argument for the machine being engineered so that the remaining leg of the pentagon, the ignition source, is genuinely absent.",
        ],
      },
      {
        heading: "Removing ignition sources from the path",
        body: [
          "This means the whole collection path, not just the motor. An electric unit built for the classification addresses the motor and switching. A pneumatic unit removes electrical components from the recovery unit entirely. Either way, the hose, tools, container and filter housing are part of the path and are specified accordingly.",
          "Mechanical sparks matter too. Material that can strike or abrade inside the machine, or foreign objects drawn in with the dust, are ignition sources in their own right. Smooth internal construction without ledges where material collects addresses both ignition and the accumulation that feeds it.",
        ],
      },
      {
        heading: "Static control as a system",
        body: [
          "Vacuuming generates static charge because material moves at speed through a hose. This happens whether the unit is electric or pneumatic, which is why static control is specified independently of the power source.",
          "The requirement is a continuous conductive path, grounded and bonded from the tool through the hose and machine to the container — a complete circuit rather than a grounded machine with a non-conductive hose attached to it. Checking that path is a routine maintenance item, because a break in it is not visible and the machine will keep working normally without it.",
        ],
      },
      {
        heading: "Preventing the cloud inside the machine",
        body: [
          "For some materials the strategy goes further than removing ignition sources: the aim becomes ensuring the dust never exists as a dry dispersed cloud inside the unit at all. Immersion separation does this by drawing material into a liquid bath so it is wetted on capture.",
          "This is material-dependent and it is not universally applicable, because some materials react with water. Whether it is appropriate is a property of the specific dust, established by characterising it — which is another reason material identification comes before equipment selection.",
        ],
      },
      {
        heading: "What happens after collection",
        body: [
          "Collected combustible dust is still combustible dust, now concentrated in a container. A full container standing in the plant is an accumulation in its own right, and carbonaceous materials in particular can hold a deep-seated smoulder that surfaces hours later.",
          "The specification therefore includes how the container is removed, sealed, transported and emptied, and where it is stored in the meantime. Whether the material can be reclaimed or must be treated as regulated waste is a separate question that depends on the material and on local requirements.",
        ],
      },
    ],
    callout: {
      heading: "Testing determines the material's behaviour",
      body: [
        "Whether a dust is combustible, how severely, and whether it can be safely wetted are determined by testing the actual material, not by category. Facilities frequently find that a material assumed to be benign has a combustible fine fraction.",
        "Where a Dust Hazard Analysis exists, its conclusions govern the specification. This guide describes how equipment selection follows from those conclusions; it does not replace them.",
      ],
    },
    faqs: [
      {
        question: "Is sweeping a reasonable alternative?",
        answer:
          "Sweeping raises dust into the air, which is the condition to avoid, and it tends to move material rather than remove it. Removal and containment is the objective, which is what a properly specified vacuum provides.",
      },
      {
        question: "Why is compressed air blowdown discouraged?",
        answer:
          "Because it does not remove anything. It disperses settled material into a cloud and relocates it, frequently into places that are harder to clean. It converts a layer — which is a manageable hazard — into a dispersed cloud, which is not.",
      },
      {
        question: "Does grounding the machine cover the static requirement?",
        answer:
          "Not on its own. The path needs to be continuous from the tool through the hose to the container. A grounded machine with a non-conductive hose leaves the charge generated in the hose with nowhere to go.",
      },
      {
        question: "Can the collected dust be reused?",
        answer:
          "Sometimes, depending on the material, the contamination it has picked up and the process it would return to. Where it cannot be reclaimed it is usually handled as regulated waste, which depends on the material and local requirements.",
      },
    ],
    related: [
      { label: "Combustible dust vacuums", href: "/combustible-dust" },
      { label: "How dust explosions work", href: "/guides/dust-explosion-basics" },
      { label: "Sources of ignition", href: "/guides/sources-of-ignition" },
      { label: "Recovered dust: reclaim or dispose?", href: "/guides/recovered-dust-disposal-and-reclaim" },
      { label: "Get a quote", href: "/get-a-quote" },
    ],
  },

  {
    slug: "how-to-size-an-industrial-vacuum",
    name: "Sizing an industrial vacuum",
    title: "Sizing an industrial vacuum: airflow, vacuum and the trade-off",
    eyebrow: "Buying guide",
    minutes: 7,
    seo: {
      title: "How to Size an Industrial Vacuum System",
      description:
        "Airflow and vacuum pressure do different jobs and trade against each other. How material density, hose length, duty cycle and capacity combine into a specification that performs on the floor.",
    },
    heroIntro:
      "Sizing goes wrong in two directions, and undersizing is not the more common one. Machines are regularly specified with more capability than the application needs, in configurations that cost airflow where airflow was the thing that mattered. Understanding what each parameter actually does makes the trade-offs visible.",
    keyPoints: [
      "Airflow moves material along; vacuum pressure lifts and dislodges it",
      "The two trade against each other — more of one usually costs the other",
      "Hose length and diameter change performance more than most expect",
      "Capacity is limited by handling weight, not container volume",
    ],
    sections: [
      {
        heading: "What airflow and vacuum each do",
        body: [
          "Airflow is volume of air moved per unit time. It is what carries material along the hose once it has been picked up, and it is what keeps material in suspension over a distance. Applications involving light material, long hose runs or large surface areas depend on airflow.",
          "Vacuum pressure is the pressure differential the unit can generate. It is what lifts material initially and what dislodges it from where it has settled or packed. Dense material, deep accumulations and material lifted vertically depend on vacuum pressure.",
        ],
      },
      {
        heading: "The trade-off",
        body: [
          "These parameters trade against each other in practical machines. A configuration optimised for high vacuum tends to move less air; one optimised for high airflow tends to generate less differential. Specifying for a headline figure in one dimension frequently costs performance in the other, and which one you needed becomes apparent only in use.",
          "The question that resolves it is what the application actually demands. Recovering fine light dust across a large floor is an airflow problem. Pulling dense metal fines out of a machine sump is a vacuum problem. Many real applications need a workable balance rather than a maximum of either.",
        ],
      },
      {
        heading: "Hose length, diameter and fittings",
        body: [
          "Every metre of hose costs performance, and the loss is not linear — it accumulates faster than a simple proportion. So does every bend, fitting and reduction. A unit that performs well on a short hose can disappoint on a long one, and the specification is for the whole assembly rather than the machine alone.",
          "Diameter is the parameter most often got wrong. A narrow hose raises velocity, which helps keep material in suspension, but it restricts volume and clogs more readily with coarse material. A wide hose moves more air but may not sustain the velocity needed to keep heavy material moving. Matching diameter to material is part of sizing, not an accessory decision.",
        ],
      },
      {
        heading: "Duty cycle and thermal reality",
        body: [
          "A unit specified for intermittent use and then run continuously will not deliver its rated performance for long. Continuous duty is a design requirement rather than a usage pattern, affecting motor selection, cooling and filter sizing.",
          "This matters most where a vacuum quietly becomes part of the process rather than a housekeeping tool — connected to a machine and running whenever that machine runs. That is a continuous-duty application even though nobody specified it as one, and it is worth identifying before rather than after.",
        ],
      },
      {
        heading: "Capacity, in practice",
        body: [
          "Container capacity is set by how much material accumulates between emptying events, but the binding constraint is usually how that container is handled. Dense material makes weight the limit long before volume is. A container sized generously on paper can be one that nobody can move when full.",
          "Filter area belongs in the sizing conversation too. Generous filter area keeps face velocity low, which sustains airflow as the filter loads and lengthens the interval between changes. Where change-out is a handling and exposure event, that interval has value beyond convenience.",
        ],
      },
    ],
    callout: {
      heading: "Figures come from the datasheet",
      body: [
        "Airflow, vacuum, motor, dimensions and filter area are model-specific and are stated on the datasheet for that model. This guide describes how to reason about them rather than quoting figures that would vary by configuration.",
        "Where an application is genuinely borderline, describing the material, the distances and the duty cycle produces a better recommendation than comparing headline numbers.",
      ],
    },
    faqs: [
      {
        question: "Should I specify for maximum suction?",
        answer:
          "Rarely. Airflow and vacuum trade against each other, so maximising one costs the other. The better question is which the application needs — light material over distance needs airflow, dense material from depth needs vacuum.",
      },
      {
        question: "How much does hose length matter?",
        answer:
          "More than most specifications assume, and the loss accumulates faster than a simple proportion. Bends, fittings and reductions add to it. Size for the assembly you will actually use, not the machine alone.",
      },
      {
        question: "What size hose should I use?",
        answer:
          "It depends on the material. Narrow hose sustains velocity and suits fine dense material but restricts volume and clogs with coarse material. Wider hose moves more air but may not keep heavy material moving. Match it to what you are recovering.",
      },
      {
        question: "Does a bigger container mean fewer interruptions?",
        answer:
          "Only if it remains handleable when full. With dense material, weight becomes the limit before volume does, and an unmanageable container tends to get emptied early anyway.",
      },
    ],
    related: [
      { label: "Industrial Vacuums", href: "/products/industrial-vacuums" },
      { label: "Electric vs pneumatic", href: "/guides/electric-vs-pneumatic-vacuums" },
      { label: "HEPA vs ULPA", href: "/guides/hepa-vs-ulpa-filtration" },
      { label: "Accessories", href: "/products/accessories" },
      { label: "Get a quote", href: "/get-a-quote" },
    ],
  },
];
