import type { GuideArticle } from "@/components/templates/guide-article";

/**
 * Industry and material selection guides, plus grounding & bonding.
 *
 * Integrity rules as guides.ts:
 * - No Kst, MIE, MEC or numeric threshold values; behaviour is referred to
 *   testing of the actual material.
 * - No clause numbers or asserted standard requirements.
 * - Certification is stated per scope from certification.ts and never merged.
 *   Group E is inside the EX1 scope only, which is the single fact that decides
 *   line eligibility in metalworking, aerospace, foundry and battery work — so
 *   those guides say so explicitly rather than leaving it to be inferred.
 * - No performance figures for any model; those come from the datasheet.
 */
export const INDUSTRY_SELECTION_GUIDES: GuideArticle[] = [
  {
    slug: "grounding-and-bonding",
    name: "Grounding & bonding",
    title: "Grounding and bonding a vacuum: the path, not the plug",
    eyebrow: "Engineering",
    minutes: 7,
    seo: {
      title: "Grounding & Bonding for Vacuum Recovery",
      description:
        "Static is generated by vacuuming itself. Why the requirement is a continuous conductive path from tool to container, and why a grounded machine alone does not achieve it.",
    },
    heroIntro:
      "This is the control most often assumed rather than verified. Vacuuming generates static charge as a matter of physics — material moving at speed through a hose separates charge whether the unit is electric or pneumatic — and the requirement is not a grounded machine. It is a continuous conductive path from the tool at the far end all the way to the collected material.",
    keyPoints: [
      "Vacuuming generates charge regardless of what drives the airflow",
      "The requirement is a continuous path, not a grounded chassis",
      "A non-conductive hose breaks the path invisibly",
      "The equipment keeps working normally when the path has failed",
    ],
    sections: [
      {
        heading: "Where the charge comes from",
        body: [
          "Charge separation happens when dissimilar materials move against each other and part. A vacuum does that continuously and by design: particles travelling at velocity along a hose wall, striking bends, separating and recombining. The faster the airflow and the drier the material, the more charge accumulates.",
          "This is why the power source is irrelevant to the static question. An air-operated unit with no electrical components anywhere on it generates static in its hose exactly as an electric one does. Removing the motor removes an ignition source; it does not remove this one.",
        ],
      },
      {
        heading: "Why a grounded machine is not enough",
        body: [
          "The common arrangement is a machine with a grounding conductor to a known earth point, and a hose bought on convenience. Charge generated inside that hose has no route to the grounded chassis, so it accumulates on the hose and on whatever the operator is holding.",
          "The requirement is a circuit: conductive tool, conductive hose with a continuous conductive element, bonded to the machine, machine bonded and grounded, and the collection container bonded into the same path. A break anywhere in that chain leaves an isolated conductive element that can accumulate charge and discharge — which is precisely the ignition source the rest of the specification exists to eliminate.",
        ],
      },
      {
        heading: "The failure is invisible",
        body: [
          "This is what makes it worth inspecting rather than assuming. A broken bonding path produces no symptom. Suction is unchanged, the motor sounds the same, the unit picks up material exactly as it did yesterday. Nothing in normal operation indicates that the control has failed.",
          "The failure modes are ordinary: a hose replaced from general stores because the original was damaged, a tool borrowed from another machine, a bonding clamp left unattached after the unit was moved, a conductive hose whose internal element has fractured from flexing. None of these announce themselves.",
        ],
      },
      {
        heading: "What this means for accessories",
        body: [
          "On a certified unit this is not only a static question — it is a certification question. Where the listing covers the vacuum together with its hoses and tools, substituting third-party accessories takes the unit outside the scope of that listing. The unit that was assessed is no longer the unit in service.",
          "That is why static-dissipating hose and filters are specified as part of the configuration rather than as an upgrade, and why a spares policy that allows generic hose defeats an expensive certified machine for the cost of a fitting.",
        ],
      },
      {
        heading: "Making it a routine check",
        body: [
          "Continuity across the whole path is a measurable property, which makes it a suitable subject for a scheduled check rather than a visual inspection. The useful discipline is to verify the path end to end — tool to container — rather than confirming that a green wire is attached to the machine.",
          "The frequency belongs in the same programme as filter and hose inspection. Where the Dust Hazard Analysis identifies static as a credible ignition source for your material, the interval should follow from that assessment rather than from convenience.",
        ],
      },
    ],
    callout: {
      heading: "Installation follows the electrical code",
      body: [
        "Grounding and bonding are installed in accordance with the National Electrical Code, Article 250. That is an installation requirement for your facility, carried out by qualified people.",
        "The equipment side is the conductive path through the machine, hose and tools. The two have to meet, and confirming that they do is worth doing explicitly rather than assuming.",
      ],
    },
    faqs: [
      {
        question: "Does a pneumatic vacuum need grounding?",
        answer:
          "Yes. Static is generated by material moving through the hose, not by the motor. An air-operated unit with no electrical components generates charge in its hose exactly as an electric one does, so the conductive path and bonding requirement is identical.",
      },
      {
        question: "Is an anti-static hose the same as a conductive hose?",
        answer:
          "Not necessarily, and the distinction matters. What the path needs is a continuous conductive element bonded at both ends. A hose described loosely as anti-static may not provide that. Specify the hose as part of the system rather than as a consumable.",
      },
      {
        question: "How would we know the bonding path had failed?",
        answer:
          "You would not, from operation. Suction, noise and pickup are all unchanged. That is the argument for a scheduled continuity check across the full path rather than a visual inspection of the machine end.",
      },
      {
        question: "Can we fit our own hose to a certified unit?",
        answer:
          "Where the listing covers the vacuum together with its hoses and tools, no — substituting them takes the unit outside the scope of its certification. It is a small decision with a disproportionate consequence, and it usually happens in service rather than at purchase.",
      },
    ],
    related: [
      { label: "Sources of ignition", href: "/guides/sources-of-ignition" },
      { label: "Anti-static and ESD-safe vacuums", href: "/guides/esd-anti-static-vacuums" },
      { label: "UL 1203 explained", href: "/hazardous-locations/ul-1203" },
      { label: "Explosion Proof Vacuums", href: "/products/explosion-proof-vacuums" },
      { label: "Accessories", href: "/products/accessories" },
      { label: "Get a quote", href: "/get-a-quote" },
    ],
  },

  {
    slug: "vacuum-for-metal-dust",
    name: "Selecting for metal dust",
    title: "Selecting a vacuum for metal dust",
    eyebrow: "Buying guide",
    minutes: 8,
    seo: {
      title: "Choosing a Vacuum for Metal Dust",
      description:
        "Metal dust is Group E — conductive, sometimes water-reactive, sometimes pyrophoric. Why the group determines which certified line is eligible, and what else the specification has to address.",
    },
    heroIntro:
      "Metal dust is the application where the certification detail stops being paperwork and starts deciding what you can buy. Group E is the conductive metal-dust group, and it is not inside every listing — so the first question is not which vacuum, but which of them are certified for the group your material sits in.",
    keyPoints: [
      "Group E is conductive metal dust and it narrows the eligible equipment",
      "Some metals react with water — wetting cannot be assumed safe",
      "Freshly generated fines can be pyrophoric",
      "Mixing metals in one container is its own hazard",
    ],
    sections: [
      {
        heading: "Start with the group, not the machine",
        body: [
          "Class II dusts are divided into groups, and metal dust sits in Group E because it is electrically conductive. That conductivity is a hazard in its own right: accumulated metal dust can bridge and short electrical equipment, causing failures that create the ignition source everything else is designed to exclude.",
          "This matters commercially because Group E is not inside every certified scope. PrestiVac's CSA listing carries two scopes, and only one of them includes Group E — the EX1 HEPA line. The EV EX HEPA line is covered for Groups F and G only. Two units that look similar and sit in the same catalogue are not interchangeable for this application, which is why each model page states its own scope.",
        ],
      },
      {
        heading: "Water reactivity changes the method",
        body: [
          "Several metals react with water to produce hydrogen, which introduces a flammable gas into an event that was already a fire. That rules out assumptions in two directions: water is not a universal extinguishing answer, and wet or immersion recovery cannot be assumed appropriate.",
          "Immersion separation — drawing material into a liquid bath so it is wetted on capture and never forms a dry cloud inside the machine — is a genuinely effective control for some metal dusts and inappropriate for others. Which applies is a property of the specific alloy as your process generates it, established by testing rather than by the metal's general reputation.",
        ],
      },
      {
        heading: "Pyrophoric behaviour in fresh fines",
        body: [
          "Grinding, machining, polishing and blasting produce fine, freshly exposed, chemically active particles. Some can ignite spontaneously on exposure to air. The stock is stable; the swarf may not be.",
          "The practical consequence is that accumulation time matters. Material left in a machine sump or a collection container is not in the same condition it was when generated, and the interval between recovery and disposal belongs in the specification rather than being left to whoever empties it.",
        ],
      },
      {
        heading: "Do not mix metals",
        body: [
          "Different metals collected into a common container can react with each other. Dedicated recovery per material is the normal arrangement in metalworking and additive manufacturing, and it is a safety decision rather than a housekeeping preference.",
          "In additive manufacturing there is a commercial reason pointing the same way: powder is expensive, operations reclaim and re-sieve it, and a recovery method that contaminates or mixes alloys destroys the feedstock value as well as creating a hazard.",
        ],
      },
      {
        heading: "What the specification has to cover",
        body: [
          "Beyond the group and the water question: a conductive, grounded and bonded path from tool to container, because dry metal dust moving through a hose generates charge readily. Smooth internal construction without ledges where material can accumulate. A container that can be removed and sealed without a second dispersal event.",
          "Filtration matters for a reason particular to metals — many are toxic as well as combustible. Retained absolute filtration is an exposure control here, not only a housekeeping one.",
        ],
      },
    ],
    comparison: {
      heading: "What differs from an organic dust application",
      columns: ["Organic dust (Group G)", "Metal dust (Group E)"],
      rows: [
        { aspect: "Certified scope", left: "Within both PrestiVac scopes", right: "EX1 HEPA line only" },
        { aspect: "Conductivity", left: "Non-conductive", right: "Conductive — can bridge electrical equipment" },
        { aspect: "Water", left: "Generally usable", right: "May react — must be established by testing" },
        { aspect: "Fresh fines", left: "Stable", right: "May be pyrophoric" },
        { aspect: "Shared container", left: "Often acceptable", right: "Different metals can react — dedicate per material" },
        { aspect: "Filtration driver", left: "Housekeeping and hazard", right: "Also toxicity and exposure" },
      ],
    },
    callout: {
      heading: "Confirm the line against your classification",
      body: [
        "Group E coverage is the deciding factor and it differs between our two certified scopes. Bring the material and the area classification assigned by your engineer, and we will confirm which line applies.",
        "Where the material has not been characterised, testing it as your process generates it comes before the equipment decision.",
      ],
    },
    faqs: [
      {
        question: "Which PrestiVac line is certified for metal dust?",
        answer:
          "The EX1 HEPA line. Its scope on CSA Certificate 70122393 includes Class II Groups E, F and G, and Group E is the conductive metal-dust group. The EV EX HEPA line is covered for Groups F and G only, so it does not carry Group E coverage.",
      },
      {
        question: "Can we vacuum aluminium and titanium into the same unit?",
        answer:
          "Not into a shared container. Different metals collected together can react with each other, so dedicated recovery per material is the normal arrangement. In additive manufacturing it is also what protects the reclaim value of the powder.",
      },
      {
        question: "Is immersion separation right for metal dust?",
        answer:
          "For some materials, and not for others. It wets material on capture so it never forms a dry cloud inside the machine, which is effective — but several metals react with water. Whether it applies to your material is established by testing rather than assumed.",
      },
      {
        question: "Does the vacuum need to be conductive throughout?",
        answer:
          "The recovery path does. Dry metal dust moving through a hose generates charge readily, so the requirement is a continuous conductive path from tool through hose to container, bonded and grounded — not simply a grounded machine.",
      },
    ],
    related: [
      { label: "Combustible metal dust", href: "/materials/combustible-metal-dust" },
      { label: "Aluminum dust", href: "/materials/aluminum-dust" },
      { label: "Titanium dust", href: "/materials/titanium-dust" },
      { label: "Class II Groups E, F & G", href: "/hazardous-locations/class-ii-groups-e-f-g" },
      { label: "NFPA 484", href: "/hazardous-locations/nfpa-484" },
      { label: "Grounding & bonding", href: "/guides/grounding-and-bonding" },
    ],
  },

  {
    slug: "vacuum-for-pharmaceutical-powders",
    name: "Selecting for pharmaceutical powders",
    title: "Selecting a vacuum for pharmaceutical powders",
    eyebrow: "Buying guide",
    minutes: 7,
    seo: {
      title: "Vacuum Selection for Pharma Powders",
      description:
        "Pharmaceutical recovery has to satisfy two requirements at once: combustible dust control and containment. How potency, cleanability and cross-contamination shape the specification.",
    },
    heroIntro:
      "Pharmaceutical powder recovery is unusual in having two independent requirements that both have to be met by the same machine. The dust may be combustible, and the product almost certainly has a containment and cross-contamination requirement that is stricter than the safety case alone would set. Specifying for one and retrofitting the other rarely works.",
    keyPoints: [
      "Combustible dust control and containment are separate requirements",
      "Potency drives the containment specification, not the fire case",
      "Cleanability and material of construction are part of the spec",
      "Cross-contamination policy usually decides dedication per line",
    ],
    sections: [
      {
        heading: "Two requirements, one machine",
        body: [
          "Many pharmaceutical powders are combustible organic dusts — lactose, starch, microcrystalline cellulose, a wide range of actives and excipients. That puts them in Class II Group G and brings the ordinary combustible dust considerations: ignition sources, static, accumulation, area classification.",
          "Independently, the product has a containment requirement. What leaves the machine matters as much as what it picks up, because an exhaust that passes the fine fraction is redistributing active material into the room. Absolute retained filtration is therefore an exposure control in this setting rather than a refinement.",
        ],
      },
      {
        heading: "Potency sets the containment level",
        body: [
          "The containment specification follows from the occupational exposure banding your organisation applies to the compound, not from the combustibility. A material with a low exposure limit may require a containment approach — bag-in bag-out change-out, sealed transfer, dedicated equipment — that a combustible-dust assessment alone would never have called for.",
          "That is why the specification conversation should start with the compound's banding, and why a general-purpose industrial specification frequently turns out to be inadequate once the containment requirement is stated.",
        ],
      },
      {
        heading: "Cleanability is a specification item",
        body: [
          "Equipment in a pharmaceutical setting has to be cleanable to a documented standard, which puts material of construction, surface finish, weld quality and the absence of dead legs and ledges into the specification. Stainless steel construction with smooth internal surfaces is the baseline rather than an upgrade.",
          "Change-out procedure belongs here too. Every filter change is a handling and exposure event, so how the filter is removed and bagged is part of the equipment decision rather than a downstream operational detail.",
        ],
      },
      {
        heading: "Cross-contamination and dedication",
        body: [
          "Shared equipment between products is a cross-contamination route, and in pharmaceutical manufacturing the consequence is a quality and regulatory one rather than merely a housekeeping one. Dedicated units or dedicated accessory sets per line, with a documented cleaning pass between products, is the usual arrangement.",
          "The segregation policy should drive the equipment decision. Deciding how many units to buy after choosing the model tends to produce the wrong number.",
        ],
      },
      {
        heading: "Where the classification comes in",
        body: [
          "Whether an area is classified, and to what, is assigned by your own engineer as part of the facility's hazardous area assessment. Dispensing, granulation, blending and compression areas frequently are; packaging areas frequently are not.",
          "Equipment is then matched to the classification that exists. A unit appropriate for a classified dispensary is not automatically what the packing hall needs, and specifying one machine for the whole site usually means over-specifying in one place and under-specifying in another.",
        ],
      },
    ],
    callout: {
      heading: "Bring the banding and the classification",
      body: [
        "The two inputs that determine the specification are the occupational exposure banding for the compound and the area classification assigned by your engineer. With both, the model and configuration follow quickly.",
        "Combustibility for a specific powder is established by testing it as your process produces it.",
      ],
    },
    faqs: [
      {
        question: "Are pharmaceutical powders combustible?",
        answer:
          "Many are. Lactose, starch, microcrystalline cellulose and a wide range of actives and excipients behave as combustible dusts in Class II Group G. Severity for a specific powder is established by testing it as your process produces it.",
      },
      {
        question: "Does HEPA filtration satisfy the containment requirement?",
        answer:
          "It addresses what leaves the machine, which is central. Whether it is sufficient depends on the exposure banding for the compound — higher-potency materials may require a containment approach covering transfer and change-out as well as filtration.",
      },
      {
        question: "Do we need a separate unit per product?",
        answer:
          "Frequently, yes. Shared equipment is a cross-contamination route with quality and regulatory consequences, so dedicated units or accessory sets per line with a documented cleaning pass between products is the common arrangement.",
      },
      {
        question: "Is one specification enough for the whole site?",
        answer:
          "Rarely. Dispensing and granulation areas are often classified where packing areas are not, so a single specification tends to over-specify in one place and under-specify in another. Match equipment to each area's classification.",
      },
    ],
    related: [
      { label: "Pharmaceutical Vacuum Cleaners", href: "/products/pharmaceutical-vacuums" },
      { label: "Cleanroom Vacuum Cleaners", href: "/products/cleanroom-vacuums" },
      { label: "Pharmaceutical industry", href: "/industries/pharmaceutical" },
      { label: "HEPA vs ULPA", href: "/guides/hepa-vs-ulpa-filtration" },
      { label: "Gelatin powder", href: "/materials/gelatin-powder" },
      { label: "Get a quote", href: "/get-a-quote" },
    ],
  },

  {
    slug: "vacuum-for-aerospace-manufacturing",
    name: "Selecting for aerospace",
    title: "Selecting a vacuum for aerospace manufacturing",
    eyebrow: "Buying guide",
    minutes: 7,
    seo: {
      title: "Vacuum Selection for Aerospace",
      description:
        "Aerospace generates reactive metal fines and conductive composite dust in the same building. Why Group E coverage and FOD control both shape the specification.",
    },
    heroIntro:
      "Aerospace manufacturing puts two awkward materials in the same facility. Machining titanium and aluminium produces reactive metal fines that sit in the conductive dust group; trimming and sanding carbon-fibre composite produces a dust that is also conductive and abrasive. Both matter for the specification, and foreign object debris control runs underneath all of it.",
    keyPoints: [
      "Titanium and aluminium fines are Group E — narrowing the eligible line",
      "Carbon-fibre dust is conductive and abrasive",
      "FOD control makes recovery a quality requirement as well as a safety one",
      "Different materials generally need dedicated recovery",
    ],
    sections: [
      {
        heading: "Metal fines set the certification requirement",
        body: [
          "Titanium and aluminium machining produce fine, freshly exposed, chemically active particles. They are conductive, which places them in Class II Group E, and some are pyrophoric when freshly generated.",
          "Group E is the deciding factor for equipment. It is inside the EX1 HEPA scope on our CSA listing and is not inside the EV EX HEPA scope, which covers Groups F and G. Two units in the same catalogue are therefore not interchangeable for a titanium cell, and the model page for each states its own scope.",
        ],
      },
      {
        heading: "Composite dust is its own problem",
        body: [
          "Carbon-fibre dust from trimming, drilling and sanding is electrically conductive, which means accumulation can bridge and short electrical equipment quite apart from any combustion consideration. It is also highly abrasive, which shortens the life of anything it passes through.",
          "The fibres are respirable in the fine fraction, so retained absolute filtration matters for exposure as well as for housekeeping. A unit that exhausts composite fines back into the shop is redistributing both a conductivity problem and an inhalation one.",
        ],
      },
      {
        heading: "Foreign object debris",
        body: [
          "In aerospace, recovery is not only a safety control. FOD is a quality and airworthiness concern, and the discipline around it means housekeeping is already a documented process in most facilities. That works in favour of a properly specified vacuum programme, because the cleaning intervals and records frequently already exist.",
          "It also means the recovery method is judged on whether material is genuinely removed rather than relocated. Compressed-air blowdown fails on both counts here: it disperses combustible fines and it moves debris into places it should not be.",
        ],
      },
      {
        heading: "Dedication between materials",
        body: [
          "Titanium, aluminium and composite should not be collected into a common container. Different metals can react with each other, and mixing composite with metal fines complicates disposal and rules out reclaim.",
          "Where the facility also runs additive manufacturing, the same principle applies more strongly: AM powder is expensive and is reclaimed and re-sieved, so contamination destroys feedstock value as well as creating a hazard.",
        ],
      },
    ],
    callout: {
      heading: "Group E is the question to settle first",
      body: [
        "If the recovery involves titanium, aluminium or other conductive metal fines, Group E coverage determines which line is eligible. Confirm the classification of the area with your engineer and we will match the line to it.",
        "Whether a specific alloy can be safely wetted — which decides whether immersion approaches are available — is established by testing the material as your process generates it.",
      ],
    },
    faqs: [
      {
        question: "Which line is certified for titanium and aluminium fines?",
        answer:
          "The EX1 HEPA line, whose scope includes Class II Group E — the conductive metal-dust group. The EV EX HEPA line is covered for Groups F and G only and does not carry Group E coverage.",
      },
      {
        question: "Is carbon-fibre dust a combustible dust?",
        answer:
          "It is conductive and abrasive, and the fine fraction is respirable. Its behaviour as a combustible dust depends on the specific material and is established by testing. The conductivity concern — bridging electrical equipment — applies regardless.",
      },
      {
        question: "Can one unit serve a mixed machining shop?",
        answer:
          "For collection into a shared container, generally not. Different metals can react with each other and mixing composite with metal fines complicates disposal. Dedicated recovery per material is the normal arrangement.",
      },
      {
        question: "Does FOD control change the specification?",
        answer:
          "It raises the standard for what counts as removal. Methods that relocate rather than remove — sweeping, blowdown — fail the FOD requirement as well as the dust one, which usually strengthens rather than complicates the case for proper recovery.",
      },
    ],
    related: [
      { label: "Aerospace industry", href: "/industries/aerospace" },
      { label: "Titanium dust", href: "/materials/titanium-dust" },
      { label: "Aluminum dust", href: "/materials/aluminum-dust" },
      { label: "Carbon fiber dust", href: "/materials/carbon-fiber-dust" },
      { label: "Selecting for metal dust", href: "/guides/vacuum-for-metal-dust" },
      { label: "Get a quote", href: "/get-a-quote" },
    ],
  },

  {
    slug: "vacuum-for-battery-manufacturing",
    name: "Selecting for battery manufacturing",
    title: "Selecting a vacuum for battery manufacturing",
    eyebrow: "Buying guide",
    minutes: 7,
    seo: {
      title: "Vacuum Selection for Battery Plants",
      description:
        "Electrode powders are conductive and fine; black mass adds toxicity and possible water reactivity. How dry rooms, Group E coverage and feedstock variability shape the specification.",
    },
    heroIntro:
      "Battery manufacturing combines several difficult properties in one building. The conductive additives that make a cell work are among the finest powders in the plant; the dry rooms that protect the chemistry keep those powders dry and readily airborne; and on the recycling side, black mass adds toxicity and possible water reactivity to the same picture.",
    keyPoints: [
      "Conductive powders can bridge electrical equipment as well as burn",
      "Dry-room humidity control keeps dust readily airborne",
      "Black mass brings Group E considerations and possible water reactivity",
      "Recycling feedstock varies, so one characterisation is not enough",
    ],
    sections: [
      {
        heading: "Conductivity is the recurring theme",
        body: [
          "Carbon blacks and fine graphites are blended into electrode slurries specifically for their conductivity. The dust that escapes during weighing, dumping and mixing is conductive too, which produces a hazard separate from combustion: accumulation on and inside electrical equipment can bridge conductors, causing tracking and failure.",
          "That is a reliability problem and a way of creating an ignition source in an area designed to have none. Carbonaceous additives sit in Group F, which is inside both PrestiVac certified scopes — but metal-bearing powders in the same building may not be.",
        ],
      },
      {
        heading: "Dry rooms work against you",
        body: [
          "Electrode areas are humidity-controlled because moisture damages the chemistry. That control has a side effect for housekeeping: the powder stays dry, which keeps it readily airborne and increases static generation as it moves through hoses and transfer points.",
          "So the conditions that protect the product also make the dust harder to contain, and the static path becomes more important rather than less. A continuous conductive path from tool to container is not optional in a dry room.",
        ],
      },
      {
        heading: "Black mass is the demanding case",
        body: [
          "On the recycling side, black mass is the fine fraction recovered from shredded cells — a mixture containing lithium, nickel, cobalt, manganese and graphite. It is conductive, which brings Group E considerations. The metals carry exposure limits, so retained filtration is an exposure control. Lithium compounds may be water-reactive, so wet methods cannot be assumed safe.",
          "Group E is the fact that decides equipment eligibility: it is inside the EX1 HEPA scope and not inside the EV EX HEPA scope. For black mass recovery, that narrows the eligible line before any other consideration.",
        ],
      },
      {
        heading: "Feedstock variability",
        body: [
          "Recycling feedstock is whatever cells arrived. Chemistry, metal content and reactivity are not constant between batches, so a characterisation carried out once describes a consignment rather than an ongoing stream.",
          "That argues for building periodic retesting into the programme rather than treating the first assessment as permanent, and for specifying equipment against the most demanding composition the site expects to handle rather than the average one.",
        ],
      },
      {
        heading: "Residual energy upstream",
        body: [
          "Incompletely discharged cells retaining stored energy is a recognised problem in this sector and has produced thermal events during shredding and handling. That is a process-control question upstream of housekeeping, but it shapes the ignition-source assessment for the whole area — and therefore the classification the equipment has to match.",
          "It is worth confirming where the classification boundary sits relative to the shredding line before specifying, because that is frequently where it changes.",
        ],
      },
    ],
    callout: {
      heading: "Confirm per material, not per building",
      body: [
        "A battery plant frequently handles both carbonaceous additives (Group F, inside both scopes) and metal-bearing powders (Group E, inside the EX1 scope only). Confirming coverage per material rather than per site avoids specifying one line for an application it is not certified for.",
        "Whether black mass can be safely wetted is a property of the material and is established by testing, revisited as feedstock changes.",
      ],
    },
    faqs: [
      {
        question: "Which line is certified for black mass?",
        answer:
          "Group E considerations apply because of the conductive metal content, and Group E is inside the EX1 HEPA scope on CSA Certificate 70122393 — not inside the EV EX HEPA scope, which covers Groups F and G only.",
      },
      {
        question: "Are conductive carbon additives in the same group?",
        answer:
          "No. Carbon blacks and graphites are carbonaceous, which is Group F, and Group F is inside both of our certified scopes. That is why coverage should be confirmed per material rather than assumed for the whole plant.",
      },
      {
        question: "Why does dry-room operation matter for housekeeping?",
        answer:
          "Humidity control keeps the powder dry, which keeps it readily airborne and increases static generation through hoses and transfer points. The conditions protecting the chemistry make the dust harder to contain.",
      },
      {
        question: "Can black mass be recovered wet?",
        answer:
          "Not without establishing the material's behaviour first. Lithium compounds may be water-reactive. Because recycling feedstock varies between batches, that is worth revisiting rather than testing once.",
      },
    ],
    related: [
      { label: "Battery Manufacturing", href: "/industries/battery" },
      { label: "Battery black mass", href: "/materials/battery-black-mass" },
      { label: "Conductive carbon", href: "/materials/conductive-carbon" },
      { label: "Graphite dust", href: "/materials/graphite-dust" },
      { label: "Selecting for metal dust", href: "/guides/vacuum-for-metal-dust" },
      { label: "Get a quote", href: "/get-a-quote" },
    ],
  },
];
